export const nav = [
  {
    text: '分布式理论',
    link: '/distributed-theory/',
    items: [
      { text: '🔬 CAP 与 BASE 理论', link: '/distributed-theory/cap-base/' },
      { text: '🔗 一致性模型（线性/顺序/因果/最终）', link: '/distributed-theory/consistency-models/' },
      { text: '🤝 共识算法（Paxos/Raft/ZAB）', link: '/distributed-theory/consensus/' },
      { text: '🔄 分布式事务（2PC/3PC/TCC/Saga/AT）', link: '/distributed-theory/distributed-transaction/' },
      { text: '📊 副本与分区（Quorum/Hint/Hinted Handoff）', link: '/distributed-theory/replication-partitioning/' },
      { text: '📡 Gossip 与故障检测（Phi Accrual）', link: '/distributed-theory/gossip-failure/' },
      { text: '🪪 幂等性与无状态设计', link: '/distributed-theory/idempotency/' },
      { text: '⏱️ 逻辑时钟与向量时钟', link: '/distributed-theory/logical-clock/' },
    ],
  },
  {
    text: '架构与设计模式',
    link: '/patterns/',
    items: [
      { text: '🏗️ 应用设计模式（创建/结构/行为）', link: '/patterns/application/' },
      { text: '🔀 并发设计模式（Worker Pool/Pipeline/Thread Local）', link: '/patterns/concurrency/' },
      { text: '🌐 分布式模式（Sidecar/Ambassador/Adapter/Leader-Follower）', link: '/patterns/distributed/' },
      { text: '🎨 架构风格（分层/六边形/洋葱/CQRS/事件溯源/EDA）', link: '/patterns/architectural-styles/' },
      { text: '⚙️ 微服务模式（API网关/配置中心/服务发现/断路器）', link: '/patterns/microservices/' },
      { text: '🐘 数据架构模式（Saga/CQRS/事件源/分片）', link: '/patterns/data-architecture/' },
    ],
  },
  {
    text: '系统设计核心',
    link: '/system-design/',
    items: [
      { text: '📋 设计方法论（用户故事/容量规划/延迟估算）', link: '/system-design/methodology/' },
      { text: '⚖️ 权衡分析（一致性 vs 可用性/延迟 vs 吞吐量）', link: '/system-design/tradeoffs/' },
      { text: '📈 扩展策略（垂直/水平/弹性/无状态化）', link: '/system-design/scaling/' },
      { text: '🗂️ 数据分片（范围/哈希/一致性哈希/热点处理）', link: '/system-design/sharding/' },
      { text: '⚡️ 缓存策略（穿透/击穿/雪崩/多级缓存/缓存一致性）', link: '/system-design/caching/' },
      { text: '🔀 负载均衡（四层/七层/一致性哈希/地理位置）', link: '/system-design/load-balancing/' },
      { text: '📨 消息与流系统（Kafka/Pulsus/RabbitMQ 选型与对比）', link: '/system-design/messaging/' },
      { text: '🗄️ 存储引擎（LSM Tree vs B+ Tree/WAL/SSTable）', link: '/system-design/storage-engine/' },
    ],
  },
  {
    text: '性能与JVM',
    link: '/performance-jvm/',
    items: [
      { text: '📊 性能指标（延迟/吞吐量/QPS/TP99/SLA）', link: '/performance-jvm/metrics/' },
      { text: '🧵 Java并发模型（线程/虚拟线程/Loom/结构化并发）', link: '/performance-jvm/concurrency/' },
      { text: '🗑️ 内存模型与GC进化史（G1/ZGC/Shenandoah/Epsilon）', link: '/performance-jvm/gc/' },
      { text: '⚡️ JIT编译与AOT（热点代码/逃逸分析/分层编译）', link: '/performance-jvm/jit-aot/' },
      { text: '💾 I/O模型（BIO/NIO/AIO/Netty/零拷贝）', link: '/performance-jvm/io/' },
      { text: '🔍 性能剖析（Profiling/火焰图/异步日志）', link: '/performance-jvm/profiling/' },
    ],
  },
  {
    text: '高可用与容错',
    link: '/resilience/',
    items: [
      { text: '✅ 可用性理论（SLA/SLO/SLI/错误预算/MTBF/MTTR）', link: '/resilience/theory/' },
      { text: '💥 故障模型（崩溃/遗漏/拜占庭/网络分区）', link: '/resilience/failure-models/' },
      { text: '🛡️ 容错模式（熔断/限流/降级/重试/超时/舱壁隔离）', link: '/resilience/patterns/' },
      { text: '💚 健康检查与自愈（存活探针/就绪探针/优雅关闭）', link: '/resilience/health-check/' },
      { text: '🌀 混沌工程（故障注入/爆炸半径/稳态假设）', link: '/resilience/chaos-engineering/' },
      { text: '💾 备份与灾难恢复（RPO/RTO/多活/单元化）', link: '/resilience/disaster-recovery/' },
    ],
  },
  {
    text: '可观测性',
    link: '/observability/',
    items: [
      { text: '🏛️ 三大支柱（Metrics/Logging/Tracing）', link: '/observability/three-pillars/' },
      { text: '📈 指标系统（Prometheus/时序数据库/黄金指标）', link: '/observability/metrics/' },
      { text: '📝 日志系统（ELK/Loki/结构化日志/采样）', link: '/observability/logging/' },
      { text: '🔗 链路追踪（OpenTelemetry/Jaeger/上下文传播）', link: '/observability/tracing/' },
      { text: '🔎 关联与根因分析（TraceID注入/标签联合）', link: '/observability/correlation/' },
      { text: '🚨 报警与仪表盘（PromQL/SLO报警/降噪）', link: '/observability/alerting/' },
    ],
  },
  {
    text: '云原生与基础设施',
    link: '/cloud-native/',
    items: [
      { text: '📦 容器化（Docker/镜像分层/运行时规范）', link: '/cloud-native/container/' },
      { text: '☸️ Kubernetes架构（Pod/Service/Ingress/CRD/Operator）', link: '/cloud-native/kubernetes/' },
      { text: '🕸️ 服务网格（Istio/Linkerd/边车模式/流量治理）', link: '/cloud-native/service-mesh/' },
      { text: '🏗️ 不可变基础设施与IaC（Terraform/Pulumi）', link: '/cloud-native/iac/' },
      { text: '🚀 CI/CD流水线（GitOps/ArgoCD/金丝雀/蓝绿）', link: '/cloud-native/cicd/' },
      { text: '☁️ Serverless（FaaS/冷启动/事件驱动）', link: '/cloud-native/serverless/' },
    ],
  },
  // {
  //   text: '安全架构',
  //   link: '/security/',
  //   items: [
  //     { text: '🔑 身份与访问管理（OAuth2/OIDC/SAML/JWT）', link: '/security/iam/' },
  //     { text: '👮 权限模型（RBAC/ABAC/ReBAC/OPA）', link: '/security/authorization/' },
  //     { text: '🔐 密码学应用（TLS/加密算法/HSM/密钥管理）', link: '/security/cryptography/' },
  //     { text: '🛡️ API安全（认证/限流/防重放/图灵盾）', link: '/security/api/' },
  //     { text: '🌐 网络安全（零信任/微分段/WAF/DDOS防护）', link: '/security/network/' },
  //     { text: '💻 应用安全（注入/XSS/CSRF/依赖扫描）', link: '/security/application/' },
  //     { text: '☁️ 云原生安全（容器镜像/K8s RBAC/运行时安全）', link: '/security/cloud-native/' },
  //     { text: '⚖️ 合规与隐私（GDPR/等保/SOC2/数据脱敏）', link: '/security/compliance/' },
  //   ],
  // },
  // {
  //   text: '演进与实战',
  //   link: '/evolution-cases/',
  //   items: [
  //     { text: '🛤️ 架构演进路径（单体→SOA→微服务→网格→无服务器）', link: '/evolution-cases/evolution-path/' },
  //     { text: '🚚 服务拆分与数据迁移（绞杀者模式/绞杀者/数据双写）', link: '/evolution-cases/migration/' },
  //     { text: '💰 技术债务治理（量化/优先级/重构策略）', link: '/evolution-cases/technical-debt/' },
  //     { text: '📋 架构决策记录（ADR/权衡框架）', link: '/evolution-cases/adr/' },
  //     { text: '🏛️ 知名架构解析（淘宝/微信/抖音/Netflix）', link: '/evolution-cases/famous/' },
  //     { text: '🔄 故障案例复盘（Hacker News/阿里/腾讯）', link: '/evolution-cases/postmortem/' },
  //     { text: '⚡ 极限场景设计（双十一/春晚/秒杀）', link: '/evolution-cases/extreme/' },
  //     { text: '🎯 架构师软技能（沟通/文档/技术雷达/团队赋能）', link: '/evolution-cases/soft-skills/' },
  //   ],
  // },
];
