export const cloudNativeSidebar = [
    {
        text: '容器化',
        link: '/cloud-native/container/',
        items: [
            { text: '容器化概述与演进', link: '/cloud-native/container/overview' },
            { text: 'Docker 架构深度解析', link: '/cloud-native/container/docker-architecture' },
            { text: 'Docker 镜像分层原理', link: '/cloud-native/container/image-layering' },
            { text: 'UnionFS 联合文件系统（OverlayFS/AUFS）', link: '/cloud-native/container/unionfs' },
            { text: 'Dockerfile 最佳实践', link: '/cloud-native/container/dockerfile-best-practices' },
            { text: '多阶段构建（Multi-stage Build）', link: '/cloud-native/container/multi-stage-build' },
            { text: '容器运行时规范（OCI）', link: '/cloud-native/container/oci' },
            { text: '容器运行时对比（runc/crun/gVisor/Kata）', link: '/cloud-native/container/runtimes' },
            { text: '容器网络模型（CNM/CNI）', link: '/cloud-native/container/network' },
            { text: '容器存储（Volume/Storage Driver）', link: '/cloud-native/container/storage' },
            { text: '容器资源隔离（Namespace/Cgroup）', link: '/cloud-native/container/isolation' },
            { text: 'cgroup 原理与配置', link: '/cloud-native/container/cgroup' },
            { text: 'namespace 详解（PID/Net/Mount/UTS/IPC/User）', link: '/cloud-native/container/namespace' },
            { text: '容器安全（Rootless/Seccomp/AppArmor）', link: '/cloud-native/container/security' },
            { text: '容器镜像仓库（Harbor/Docker Registry）', link: '/cloud-native/container/registry' },
            { text: '容器镜像优化与瘦身', link: '/cloud-native/container/image-optimization' },
            { text: '容器化 Java 应用最佳实践', link: '/cloud-native/container/java-container' },
            { text: 'JVM 在容器中的内存配置', link: '/cloud-native/container/jvm-in-container' },
            { text: '容器化改造实战', link: '/cloud-native/container/migration' },
        ],
    },
    {
        text: 'Kubernetes架构',
        link: '/cloud-native/kubernetes/',
        items: [
            { text: 'Kubernetes 概述与架构', link: '/cloud-native/kubernetes/overview' },
            { text: '控制平面组件（API Server/etcd/Scheduler/CM）', link: '/cloud-native/kubernetes/control-plane' },
            { text: '工作节点组件（kubelet/kube-proxy/CRI）', link: '/cloud-native/kubernetes/node-components' },
            { text: 'Pod 深度解析', link: '/cloud-native/kubernetes/pod' },
            { text: 'Pod 生命周期与钩子', link: '/cloud-native/kubernetes/pod-lifecycle' },
            { text: 'Service 详解（ClusterIP/NodePort/LoadBalancer）', link: '/cloud-native/kubernetes/service' },
            { text: 'Ingress 与 Ingress Controller', link: '/cloud-native/kubernetes/ingress' },
            { text: 'ConfigMap 与 Secret', link: '/cloud-native/kubernetes/configmap-secret' },
            { text: 'Volume 与 PVC/PV', link: '/cloud-native/kubernetes/volume' },
            { text: 'StorageClass 动态存储', link: '/cloud-native/kubernetes/storageclass' },
            { text: 'Deployment 与 ReplicaSet', link: '/cloud-native/kubernetes/deployment' },
            { text: 'StatefulSet 有状态应用', link: '/cloud-native/kubernetes/statefulset' },
            { text: 'DaemonSet 守护进程', link: '/cloud-native/kubernetes/daemonset' },
            { text: 'Job 与 CronJob', link: '/cloud-native/kubernetes/job' },
            { text: 'HPA（水平自动伸缩）', link: '/cloud-native/kubernetes/hpa' },
            { text: 'VPA（垂直自动伸缩）', link: '/cloud-native/kubernetes/vpa' },
            { text: 'CRD（自定义资源定义）', link: '/cloud-native/kubernetes/crd' },
            { text: 'Operator 模式深度解析', link: '/cloud-native/kubernetes/operator' },
            { text: 'Operator 开发实战（Kubebuilder）', link: '/cloud-native/kubernetes/operator-development' },
            { text: 'Kubernetes 网络模型', link: '/cloud-native/kubernetes/network-model' },
            { text: 'CNI 插件对比（Flannel/Calico/Cilium）', link: '/cloud-native/kubernetes/cni' },
            { text: 'NetworkPolicy 网络策略', link: '/cloud-native/kubernetes/network-policy' },
            { text: 'Kubernetes 调度器原理', link: '/cloud-native/kubernetes/scheduler' },
            { text: '调度策略与亲和性', link: '/cloud-native/kubernetes/affinity' },
            { text: '污点与容忍（Taint/Toleration）', link: '/cloud-native/kubernetes/taint-toleration' },
            { text: 'Kubernetes 安全（RBAC/ServiceAccount）', link: '/cloud-native/kubernetes/security' },
            { text: 'Pod 安全策略（PSP/PSS）', link: '/cloud-native/kubernetes/pod-security' },
            { text: 'Kubernetes 监控（Metrics Server/Prometheus）', link: '/cloud-native/kubernetes/monitoring' },
            { text: 'Kubernetes 日志收集', link: '/cloud-native/kubernetes/logging' },
            { text: 'Kubernetes 故障排查', link: '/cloud-native/kubernetes/troubleshooting' },
            { text: 'K8s 升级与版本管理', link: '/cloud-native/kubernetes/upgrade' },
            { text: '多集群管理（Federation/Karmada）', link: '/cloud-native/kubernetes/multi-cluster' },
        ],
    },
    {
        text: '服务网格',
        link: '/cloud-native/service-mesh/',
        items: [
            { text: '服务网格概述', link: '/cloud-native/service-mesh/overview' },
            { text: '服务网格 vs API 网关', link: '/cloud-native/service-mesh/vs-api-gateway' },
            { text: '边车模式（Sidecar）深度解析', link: '/cloud-native/service-mesh/sidecar' },
            { text: '服务网格架构（数据平面/控制平面）', link: '/cloud-native/service-mesh/architecture' },
            { text: 'Envoy 代理深度解析', link: '/cloud-native/service-mesh/envoy' },
            { text: 'Istio 架构深度解析', link: '/cloud-native/service-mesh/istio-architecture' },
            { text: 'Istio 安装与配置', link: '/cloud-native/service-mesh/istio-installation' },
            { text: 'Istio 流量管理（VirtualService/DestinationRule）', link: '/cloud-native/service-mesh/istio-traffic' },
            { text: '金丝雀发布与灰度发布', link: '/cloud-native/service-mesh/canary' },
            { text: 'Istio 安全（mTLS/认证/授权）', link: '/cloud-native/service-mesh/istio-security' },
            { text: 'Istio 可观测性（Kiali/Jaeger）', link: '/cloud-native/service-mesh/istio-observability' },
            { text: 'Istio 故障注入与混沌测试', link: '/cloud-native/service-mesh/istio-chaos' },
            { text: 'Linkerd 架构深度解析', link: '/cloud-native/service-mesh/linkerd' },
            { text: 'Linkerd vs Istio 对比', link: '/cloud-native/service-mesh/linkerd-vs-istio' },
            { text: 'Consul Connect 服务网格', link: '/cloud-native/service-mesh/consul' },
            { text: '服务网格性能开销分析', link: '/cloud-native/service-mesh/performance-overhead' },
            { text: '服务网格落地挑战', link: '/cloud-native/service-mesh/challenges' },
            { text: '多集群服务网格', link: '/cloud-native/service-mesh/multi-cluster' },
            { text: '服务网格与 Kubernetes 集成', link: '/cloud-native/service-mesh/k8s-integration' },
            { text: '服务网格迁移实战', link: '/cloud-native/service-mesh/migration' },
        ],
    },
    {
        text: '不可变基础设施与IaC',
        link: '/cloud-native/iac/',
        items: [
            { text: '不可变基础设施概述', link: '/cloud-native/iac/immutable-infra' },
            { text: '可变 vs 不可变基础设施', link: '/cloud-native/iac/mutable-vs-immutable' },
            { text: 'IaC（基础设施即代码）概述', link: '/cloud-native/iac/overview' },
            { text: 'IaC 最佳实践', link: '/cloud-native/iac/best-practices' },
            { text: '声明式 vs 命令式 IaC', link: '/cloud-native/iac/declarative-vs-imperative' },
            { text: 'Terraform 架构深度解析', link: '/cloud-native/iac/terraform-architecture' },
            { text: 'Terraform 核心语法', link: '/cloud-native/iac/terraform-syntax' },
            { text: 'Terraform State 管理', link: '/cloud-native/iac/terraform-state' },
            { text: 'Terraform 模块化设计', link: '/cloud-native/iac/terraform-modules' },
            { text: 'Terraform Provider 开发', link: '/cloud-native/iac/terraform-provider' },
            { text: 'Terraform 多环境管理', link: '/cloud-native/iac/terraform-environments' },
            { text: 'Pulumi 架构深度解析', link: '/cloud-native/iac/pulumi' },
            { text: 'Pulumi vs Terraform 对比', link: '/cloud-native/iac/pulumi-vs-terraform' },
            { text: 'AWS CloudFormation', link: '/cloud-native/iac/cloudformation' },
            { text: 'Ansible 配置管理', link: '/cloud-native/iac/ansible' },
            { text: 'Packer 镜像构建', link: '/cloud-native/iac/packer' },
            { text: '镜像不可变最佳实践', link: '/cloud-native/iac/immutable-image' },
            { text: 'IaC 安全与合规', link: '/cloud-native/iac/security' },
            { text: 'IaC 测试策略', link: '/cloud-native/iac/testing' },
            { text: 'Terratest 基础设施测试', link: '/cloud-native/iac/terratest' },
            { text: 'IaC 与 CI/CD 集成', link: '/cloud-native/iac/cicd-integration' },
        ],
    },
    {
        text: 'CI/CD流水线',
        link: '/cloud-native/cicd/',
        items: [
            { text: 'CI/CD 概述与演进', link: '/cloud-native/cicd/overview' },
            { text: 'CI/CD 核心原则', link: '/cloud-native/cicd/principles' },
            { text: 'GitOps 理念深度解析', link: '/cloud-native/cicd/gitops' },
            { text: 'GitOps vs 传统 CI/CD', link: '/cloud-native/cicd/gitops-vs-traditional' },
            { text: 'ArgoCD 架构深度解析', link: '/cloud-native/cicd/argocd' },
            { text: 'ArgoCD 部署与配置', link: '/cloud-native/cicd/argocd-deployment' },
            { text: 'ArgoCD 应用管理', link: '/cloud-native/cicd/argocd-application' },
            { text: 'ArgoCD 多集群管理', link: '/cloud-native/cicd/argocd-multi-cluster' },
            { text: 'Flux 架构与使用', link: '/cloud-native/cicd/flux' },
            { text: 'ArgoCD vs Flux 对比', link: '/cloud-native/cicd/argocd-vs-flux' },
            { text: 'Jenkins Pipeline 最佳实践', link: '/cloud-native/cicd/jenkins-pipeline' },
            { text: 'GitLab CI/CD 深度解析', link: '/cloud-native/cicd/gitlab-ci' },
            { text: 'GitHub Actions 深度解析', link: '/cloud-native/cicd/github-actions' },
            { text: 'Tekton 云原生 CI/CD', link: '/cloud-native/cicd/tekton' },
            { text: '金丝雀发布（Canary）策略', link: '/cloud-native/cicd/canary' },
            { text: '蓝绿部署（Blue-Green）策略', link: '/cloud-native/cicd/blue-green' },
            { text: '滚动更新（Rolling Update）策略', link: '/cloud-native/cicd/rolling-update' },
            { text: 'A/B 测试与灰度发布', link: '/cloud-native/cicd/ab-testing' },
            { text: '发布策略选型矩阵', link: '/cloud-native/cicd/deployment-strategies' },
            { text: '特性开关（Feature Toggle）', link: '/cloud-native/cicd/feature-toggle' },
            { text: 'CI/CD 安全（Secret管理/镜像扫描）', link: '/cloud-native/cicd/security' },
            { text: 'CI/CD 度量与优化', link: '/cloud-native/cicd/metrics' },
            { text: '流水线即代码（Pipeline as Code）', link: '/cloud-native/cicd/pipeline-as-code' },
        ],
    },
    {
        text: 'Serverless',
        link: '/cloud-native/serverless/',
        items: [
            { text: 'Serverless 概述', link: '/cloud-native/serverless/overview' },
            { text: 'Serverless vs 传统架构', link: '/cloud-native/serverless/vs-traditional' },
            { text: 'FaaS（函数即服务）详解', link: '/cloud-native/serverless/faas' },
            { text: 'Serverless 核心概念', link: '/cloud-native/serverless/concepts' },
            { text: '冷启动（Cold Start）问题', link: '/cloud-native/serverless/cold-start' },
            { text: '冷启动优化策略', link: '/cloud-native/serverless/cold-start-optimization' },
            { text: '热启动与实例复用', link: '/cloud-native/serverless/warm-start' },
            { text: '事件驱动架构（EDA）', link: '/cloud-native/serverless/event-driven' },
            { text: 'AWS Lambda 深度解析', link: '/cloud-native/serverless/aws-lambda' },
            { text: 'AWS Lambda 最佳实践', link: '/cloud-native/serverless/lambda-best-practices' },
            { text: 'Azure Functions', link: '/cloud-native/serverless/azure-functions' },
            { text: 'Google Cloud Functions', link: '/cloud-native/serverless/gcp-functions' },
            { text: 'Knative 架构深度解析', link: '/cloud-native/serverless/knative' },
            { text: 'Knative Serving 详解', link: '/cloud-native/serverless/knative-serving' },
            { text: 'Knative Eventing 详解', link: '/cloud-native/serverless/knative-eventing' },
            { text: 'OpenFaaS 架构与使用', link: '/cloud-native/serverless/openfaas' },
            { text: 'Kubeless 架构与使用', link: '/cloud-native/serverless/kubeless' },
            { text: 'Serverless 框架对比', link: '/cloud-native/serverless/comparison' },
            { text: 'Serverless 可观测性', link: '/cloud-native/serverless/observability' },
            { text: 'Serverless 成本分析', link: '/cloud-native/serverless/cost-analysis' },
            { text: 'Serverless 冷启动案例', link: '/cloud-native/serverless/cold-start-cases' },
            { text: 'Serverless 企业落地挑战', link: '/cloud-native/serverless/challenges' },
            { text: 'Serverless + Kubernetes 混合架构', link: '/cloud-native/serverless/hybrid' },
        ],
    },
];