export const distributedTheorySidebar = [
    {
        text: 'CAP 与 BASE 理论',
        link: '/distributed-theory/cap-base/',
        items: [
            { text: 'CAP 定理的数学证明', link: '/distributed-theory/cap-base/proof' },
            { text: 'CP vs AP 系统选型', link: '/distributed-theory/cap-base/cp-vs-ap' },
            { text: 'BASE 理论详解', link: '/distributed-theory/cap-base/base' },
            { text: '真实系统 CAP 分析（ZooKeeper/Eureka/Redis）', link: '/distributed-theory/cap-base/real-systems' },
            { text: 'CAP 常见误区', link: '/distributed-theory/cap-base/misconceptions' },
        ],
    },
    {
        text: '一致性模型',
        link: '/distributed-theory/consistency-models/',
        items: [
            { text: '强一致性（线性一致性）', link: '/distributed-theory/consistency-models/linearizability' },
            { text: '顺序一致性', link: '/distributed-theory/consistency-models/sequential' },
            { text: '因果一致性', link: '/distributed-theory/consistency-models/causal' },
            { text: '最终一致性', link: '/distributed-theory/consistency-models/eventual' },
            { text: '单调读与单调写', link: '/distributed-theory/consistency-models/monotonic' },
            { text: '一致性级别对比矩阵', link: '/distributed-theory/consistency-models/comparison' },
        ],
    },
    {
        text: '共识算法',
        link: '/distributed-theory/consensus/',
        items: [
            { text: 'Paxos 算法详解', link: '/distributed-theory/consensus/paxos' },
            { text: 'Raft 算法详解', link: '/distributed-theory/consensus/raft' },
            { text: 'ZAB 协议详解', link: '/distributed-theory/consensus/zab' },
            { text: 'Raft 与 Paxos 对比', link: '/distributed-theory/consensus/raft-vs-paxos' },
            { text: 'Leader 选举机制', link: '/distributed-theory/consensus/leader-election' },
            { text: '日志复制与安全性', link: '/distributed-theory/consensus/log-replication' },
            { text: '生产实践（etcd/Consul/ZooKeeper）', link: '/distributed-theory/consensus/production' },
        ],
    },
    {
        text: '分布式事务',
        link: '/distributed-theory/distributed-transaction/',
        items: [
            { text: '2PC（两阶段提交）', link: '/distributed-theory/distributed-transaction/2pc' },
            { text: '3PC（三阶段提交）', link: '/distributed-theory/distributed-transaction/3pc' },
            { text: 'TCC（Try-Confirm-Cancel）', link: '/distributed-theory/distributed-transaction/tcc' },
            { text: 'Saga 事务', link: '/distributed-theory/distributed-transaction/saga' },
            { text: 'AT 模式（Seata）', link: '/distributed-theory/distributed-transaction/at' },
            { text: '事务方案选型矩阵', link: '/distributed-theory/distributed-transaction/comparison' },
            { text: '柔性事务与刚性事务', link: '/distributed-theory/distributed-transaction/flexible-vs-rigid' },
        ],
    },
    {
        text: '副本与分区',
        link: '/distributed-theory/replication-partitioning/',
        items: [
            { text: '主从复制', link: '/distributed-theory/replication-partitioning/master-slave' },
            { text: '多主复制', link: '/distributed-theory/replication-partitioning/multi-master' },
            { text: '无主复制', link: '/distributed-theory/replication-partitioning/leaderless' },
            { text: 'Quorum 机制详解', link: '/distributed-theory/replication-partitioning/quorum' },
            { text: 'Hinted Handoff', link: '/distributed-theory/replication-partitioning/hinted-handoff' },
            { text: '读修复与反熵', link: '/distributed-theory/replication-partitioning/anti-entropy' },
            { text: '数据分区策略', link: '/distributed-theory/replication-partitioning/partitioning' },
        ],
    },
    {
        text: 'Gossip 与故障检测',
        link: '/distributed-theory/gossip-failure/',
        items: [
            { text: 'Gossip 协议原理', link: '/distributed-theory/gossip-failure/gossip-protocol' },
            { text: '流行传播与收敛性', link: '/distributed-theory/gossip-failure/convergence' },
            { text: 'Phi Accrual 故障检测', link: '/distributed-theory/gossip-failure/phi-accrual' },
            { text: 'SWIM 协议', link: '/distributed-theory/gossip-failure/swim' },
            { text: 'Cassandra 中的 Gossip 实践', link: '/distributed-theory/gossip-failure/cassandra' },
        ],
    },
    {
        text: '幂等性与无状态设计',
        link: '/distributed-theory/idempotency/',
        items: [
            { text: '幂等性定义与数学基础', link: '/distributed-theory/idempotency/definition' },
            { text: 'HTTP 幂等性（GET/PUT/DELETE/POST）', link: '/distributed-theory/idempotency/http-methods' },
            { text: '接口幂等实现方案', link: '/distributed-theory/idempotency/implementation' },
            { text: '唯一索引与乐观锁', link: '/distributed-theory/idempotency/unique-index' },
            { text: '分布式幂等（Token 机制）', link: '/distributed-theory/idempotency/token' },
            { text: '消息队列幂等消费', link: '/distributed-theory/idempotency/mq-consumer' },
            { text: '无状态设计模式', link: '/distributed-theory/idempotency/stateless' },
        ],
    },
    {
        text: '逻辑时钟与向量时钟',
        link: '/distributed-theory/logical-clock/',
        items: [
            { text: 'Lamport 逻辑时钟', link: '/distributed-theory/logical-clock/lamport' },
            { text: '向量时钟原理', link: '/distributed-theory/logical-clock/vector' },
            { text: '版本向量', link: '/distributed-theory/logical-clock/version' },
            { text: '因果关系检测', link: '/distributed-theory/logical-clock/causality' },
            { text: 'Dynamo 中的向量时钟实践', link: '/distributed-theory/logical-clock/dynamo' },
            { text: '逻辑时钟 vs 物理时钟', link: '/distributed-theory/logical-clock/vs-physical' },
        ],
    },
];
