export const evolutionCasesSidebar = [
    {
        text: '架构演进路径',
        link: '/evolution-cases/evolution-path/',
        items: [
            { text: '单体架构时代', link: '/evolution-cases/evolution-path/monolith' },
            { text: 'SOA 面向服务架构', link: '/evolution-cases/evolution-path/soa' },
            { text: '微服务时代', link: '/evolution-cases/evolution-path/microservices' },
            { text: '服务网格（Service Mesh）', link: '/evolution-cases/evolution-path/service-mesh' },
            { text: '无服务器架构（Serverless）', link: '/evolution-cases/evolution-path/serverless' },
            { text: '架构演进决策树', link: '/evolution-cases/evolution-path/decision-tree' },
        ],
    },
    {
        text: '服务拆分与数据迁移',
        link: '/evolution-cases/migration/',
        items: [
            { text: '绞杀者模式详解', link: '/evolution-cases/migration/strangler' },
            { text: '数据双写策略', link: '/evolution-cases/migration/data-double-write' },
            { text: '灰度发布与流量切换', link: '/evolution-cases/migration/gradual-rollout' },
            { text: '数据迁移回填方案', link: '/evolution-cases/migration/data-backfill' },
            { text: '分布式事务迁移', link: '/evolution-cases/migration/distributed-transaction' },
            { text: '服务依赖梳理', link: '/evolution-cases/migration/dependency-analysis' },
        ],
    },
    {
        text: '技术债务治理',
        link: '/evolution-cases/technical-debt/',
        items: [
            { text: '债务量化方法', link: '/evolution-cases/technical-debt/quantification' },
            { text: '债务优先级评估', link: '/evolution-cases/technical-debt/prioritization' },
            { text: '重构策略选择', link: '/evolution-cases/technical-debt/refactoring-strategy' },
            { text: '增量重构实践', link: '/evolution-cases/technical-debt/incremental-refactoring' },
            { text: '遗留系统现代化', link: '/evolution-cases/technical-debt/modernization' },
        ],
    },
    {
        text: '架构决策记录（ADR）',
        link: '/evolution-cases/adr/',
        items: [
            { text: 'ADR 编写规范', link: '/evolution-cases/adr/specification' },
            { text: '权衡框架与决策树', link: '/evolution-cases/adr/tradeoff-framework' },
            { text: '决策记录模板', link: '/evolution-cases/adr/template' },
            { text: '决策评审流程', link: '/evolution-cases/adr/review-process' },
            { text: '经典架构决策案例', link: '/evolution-cases/adr/cases' },
        ],
    },
    {
        text: '知名架构解析',
        link: '/evolution-cases/famous/',
        items: [
            { text: 'Google 演进史', link: '/evolution-cases/famous/google' },
            { text: 'Netflix 微服务实践', link: '/evolution-cases/famous/netflix' },
            { text: 'Uber 实时架构', link: '/evolution-cases/famous/uber' },
            { text: 'LinkedIn 架构', link: '/evolution-cases/famous/linkedin' },
            { text: 'Stripe 支付架构', link: '/evolution-cases/famous/stripe' },
            { text: 'Twitter 流架构', link: '/evolution-cases/famous/twitter' },
            { text: '淘宝架构演进', link: '/evolution-cases/famous/taobao' },
            { text: '阿里中台架构', link: '/evolution-cases/famous/alibaba' },
            { text: '字节推荐架构', link: '/evolution-cases/famous/bytedance' },
            { text: '抖音推荐架构', link: '/evolution-cases/famous/douyin' },
            { text: '微信海量通讯架构', link: '/evolution-cases/famous/wechat' },
            { text: '腾讯即时通讯架构', link: '/evolution-cases/famous/tencent' },
            { text: '美团本地生活架构', link: '/evolution-cases/famous/meituan' },
            { text: '滴滴出行架构', link: '/evolution-cases/famous/didi' },
            { text: '快手短视频架构', link: '/evolution-cases/famous/kuaishou' }
        ],
    },
    {
        text: '故障案例复盘',
        link: '/evolution-cases/postmortem/',
        items: [
            { text: 'Hacker News 数据库宕机', link: '/evolution-cases/postmortem/hacker-news' },
            { text: '阿里光缆故障', link: '/evolution-cases/postmortem/alibaba' },
            { text: '腾讯服务雪崩', link: '/evolution-cases/postmortem/tencent' },
            { text: '故障复盘方法论', link: '/evolution-cases/postmortem/methodology' },
            { text: '故障预防体系', link: '/evolution-cases/postmortem/prevention' },
            { text: 'GitLab 删库事件', link: '/evolution-cases/postmortem/gitlab/' },
            { text: 'GitHub 降级事故', link: '/evolution-cases/postmortem/github/' },
        ],
    },
    {
        text: '极限场景设计',
        link: '/evolution-cases/extreme/',
        items: [
            { text: '双十一秒杀架构', link: '/evolution-cases/extreme/double11' },
            { text: '春晚红包架构', link: '/evolution-cases/extreme/spring-festival' },
            { text: '高并发抢购系统', link: '/evolution-cases/extreme/seckill' },
            { text: '海量数据处理', link: '/evolution-cases/extreme/big-data' },
            { text: '跨机房多活架构', link: '/evolution-cases/extreme/multi-active' },
        ],
    },
    {
        text: '架构师软技能',
        link: '/evolution-cases/soft-skills/',
        items: [
            { text: '技术沟通技巧', link: '/evolution-cases/soft-skills/communication' },
            { text: '架构文档编写', link: '/evolution-cases/soft-skills/documentation' },
            { text: '技术雷达设计', link: '/evolution-cases/soft-skills/tech-radar' },
            { text: '团队赋能方法', link: '/evolution-cases/soft-skills/team-empowerment' },
            { text: '向上沟通与汇报', link: '/evolution-cases/soft-skills/escalation' },
        ],
    },
];
