export const observabilitySidebar = [
    {
        text: '三大支柱',
        link: '/observability/three-pillars/',
        items: [
            { text: '可观测性概述与演进', link: '/observability/three-pillars/overview' },
            { text: '三大支柱：Metrics/Logging/Tracing', link: '/observability/three-pillars/definition' },
            { text: '可观测性 vs 传统监控', link: '/observability/three-pillars/vs-monitoring' },
            { text: '三大支柱的关联与互补', link: '/observability/three-pillars/correlation' },
            { text: '可观测性成熟度模型', link: '/observability/three-pillars/maturity-model' },
            { text: 'OpenTelemetry 统一标准', link: '/observability/three-pillars/opentelemetry' },
            { text: '可观测性成本与采样策略', link: '/observability/three-pillars/cost-sampling' },
            { text: '可观测性团队建设', link: '/observability/three-pillars/team-culture' },
        ],
    },
    {
        text: '指标系统',
        link: '/observability/metrics/',
        items: [
            { text: '指标系统概述', link: '/observability/metrics/overview' },
            { text: '指标类型（Counter/Gauge/Histogram/Summary）', link: '/observability/metrics/types' },
            { text: '黄金指标（延迟/流量/错误/饱和度）', link: '/observability/metrics/golden-signals' },
            { text: 'USE 方法（利用率/饱和度/错误）', link: '/observability/metrics/use-method' },
            { text: 'RED 方法（速率/错误/延迟）', link: '/observability/metrics/red-method' },
            { text: 'Prometheus 架构深度解析', link: '/observability/metrics/prometheus-architecture' },
            { text: 'Prometheus 数据模型', link: '/observability/metrics/prometheus-data-model' },
            { text: 'Exporter 生态与开发', link: '/observability/metrics/exporter' },
            { text: 'Micrometer 指标采集', link: '/observability/metrics/micrometer' },
            { text: '时序数据库原理（TSDB）', link: '/observability/metrics/tsdb' },
            { text: 'VictoriaMetrics vs Prometheus', link: '/observability/metrics/victoriametrics' },
            { text: 'Thanos 长期存储', link: '/observability/metrics/thanos' },
            { text: '指标聚合与降采样', link: '/observability/metrics/aggregation' },
            { text: '指标基数问题与解决', link: '/observability/metrics/cardinality' },
            { text: '业务指标埋点设计', link: '/observability/metrics/business-metrics' },
        ],
    },
    {
        text: '日志系统',
        link: '/observability/logging/',
        items: [
            { text: '日志系统概述', link: '/observability/logging/overview' },
            { text: '结构化日志（Structured Logging）', link: '/observability/logging/structured' },
            { text: '日志级别与最佳实践', link: '/observability/logging/levels' },
            { text: '日志采样（Log Sampling）策略', link: '/observability/logging/sampling' },
            { text: 'ELK Stack 架构深度解析', link: '/observability/logging/elk' },
            { text: 'Elasticsearch 日志存储', link: '/observability/logging/elasticsearch' },
            { text: 'Logstash 与 Filebeat', link: '/observability/logging/logstash-filebeat' },
            { text: 'Kibana 可视化', link: '/observability/logging/kibana' },
            { text: 'Loki 架构深度解析', link: '/observability/logging/loki' },
            { text: 'Loki vs ELK 对比', link: '/observability/logging/loki-vs-elk' },
            { text: '日志采集器对比（Fluentd/Vector/Logstash）', link: '/observability/logging/collectors' },
            { text: '日志索引与查询优化', link: '/observability/logging/query-optimization' },
            { text: '日志生命周期管理', link: '/observability/logging/lifecycle' },
            { text: '日志成本控制', link: '/observability/logging/cost-control' },
            { text: '敏感日志脱敏', link: '/observability/logging/desensitization' },
        ],
    },
    {
        text: '链路追踪',
        link: '/observability/tracing/',
        items: [
            { text: '链路追踪概述', link: '/observability/tracing/overview' },
            { text: 'Trace/Span/Context 核心概念', link: '/observability/tracing/concepts' },
            { text: 'OpenTelemetry 架构', link: '/observability/tracing/opentelemetry' },
            { text: 'OpenTelemetry SDK 使用', link: '/observability/tracing/opentelemetry-sdk' },
            { text: 'Jaeger 架构深度解析', link: '/observability/tracing/jaeger' },
            { text: 'Jaeger 部署与配置', link: '/observability/tracing/jaeger-deployment' },
            { text: 'Zipkin 架构与使用', link: '/observability/tracing/zipkin' },
            { text: 'Tempo 架构与使用', link: '/observability/tracing/tempo' },
            { text: '链路追踪对比（Jaeger/Zipkin/Tempo）', link: '/observability/tracing/comparison' },
            { text: '上下文传播（Context Propagation）', link: '/observability/tracing/context-propagation' },
            { text: 'W3C Trace Context 标准', link: '/observability/tracing/w3c-trace' },
            { text: 'Baggage 与业务数据传递', link: '/observability/tracing/baggage' },
            { text: 'Java Agent 无侵入埋点', link: '/observability/tracing/java-agent' },
            { text: '手动埋点与自定义 Span', link: '/observability/tracing/manual-instrumentation' },
            { text: '异步链路追踪', link: '/observability/tracing/async-tracing' },
            { text: '采样策略（头部采样/尾部采样）', link: '/observability/tracing/sampling' },
            { text: '自适应采样', link: '/observability/tracing/adaptive-sampling' },
            { text: '链路追踪性能开销', link: '/observability/tracing/overhead' },
        ],
    },
    {
        text: '关联与根因分析',
        link: '/observability/correlation/',
        items: [
            { text: '可观测性关联概述', link: '/observability/correlation/overview' },
            { text: 'TraceID 注入日志', link: '/observability/correlation/traceid-injection' },
            { text: 'MDC（Mapped Diagnostic Context）', link: '/observability/correlation/mdc' },
            { text: '日志与 Trace 关联实现', link: '/observability/correlation/log-trace-correlation' },
            { text: 'Metrics 与 Trace 关联', link: '/observability/correlation/metrics-trace-correlation' },
            { text: '标签联合查询', link: '/observability/correlation/label-join' },
            { text: '服务拓扑自动发现', link: '/observability/correlation/service-topology' },
            { text: '根因分析（RCA）方法论', link: '/observability/correlation/rca-methodology' },
            { text: '根因分析算法', link: '/observability/correlation/rca-algorithms' },
            { text: '智能告警与根因推荐', link: '/observability/correlation/aiops' },
            { text: '故障根因定位流程', link: '/observability/correlation/rca-process' },
            { text: '根因分析案例实战', link: '/observability/correlation/rca-cases' },
        ],
    },
    {
        text: '报警与仪表盘',
        link: '/observability/alerting/',
        items: [
            { text: '报警系统概述', link: '/observability/alerting/overview' },
            { text: 'PromQL 深度语法', link: '/observability/alerting/promql' },
            { text: 'PromQL 常见查询模式', link: '/observability/alerting/promql-patterns' },
            { text: 'Prometheus 报警规则配置', link: '/observability/alerting/alert-rules' },
            { text: 'Alertmanager 架构', link: '/observability/alerting/alertmanager' },
            { text: '报警分组/抑制/静默', link: '/observability/alerting/grouping-silence' },
            { text: '报警路由与接收器', link: '/observability/alerting/routing' },
            { text: 'SLO 报警设计', link: '/observability/alerting/slo-alerting' },
            { text: '燃烧率报警（Burn Rate）', link: '/observability/alerting/burn-rate' },
            { text: '多窗口燃烧率报警', link: '/observability/alerting/multi-window-burn-rate' },
            { text: '报警降噪与去重', link: '/observability/alerting/noise-reduction' },
            { text: '报警疲劳避免策略', link: '/observability/alerting/fatigue-prevention' },
            { text: '报警有效性评估', link: '/observability/alerting/effectiveness' },
            { text: 'Grafana 仪表盘设计', link: '/observability/alerting/grafana' },
            { text: 'Grafana 面板类型与选择', link: '/observability/alerting/grafana-panels' },
            { text: '仪表盘设计最佳实践', link: '/observability/alerting/dashboard-best-practices' },
            { text: '运维 On-Call 流程', link: '/observability/alerting/oncall' },
            { text: '告警治理方法论', link: '/observability/alerting/governance' },
        ],
    },
];