export const patternsSidebar = [
    {
        text: '应用设计模式',
        link: '/patterns/application/',
        items: [
            { text: '创建型模式总览', link: '/patterns/application/creational' },
            { text: '单例模式（双重检查锁/静态内部类/枚举）', link: '/patterns/application/singleton' },
            { text: '工厂模式（简单工厂/工厂方法/抽象工厂）', link: '/patterns/application/factory' },
            { text: '建造者模式（链式调用/不可变对象）', link: '/patterns/application/builder' },
            { text: '原型模式（深拷贝/浅拷贝/克隆）', link: '/patterns/application/prototype' },
            { text: '结构型模式总览', link: '/patterns/application/structural' },
            { text: '适配器模式（类适配器/对象适配器）', link: '/patterns/application/adapter' },
            { text: '代理模式（静态代理/动态代理/CGLib）', link: '/patterns/application/proxy' },
            { text: '装饰器模式（IO流中的经典应用）', link: '/patterns/application/decorator' },
            { text: '外观模式（门面模式）', link: '/patterns/application/facade' },
            { text: '桥接模式', link: '/patterns/application/bridge' },
            { text: '组合模式（树形结构处理）', link: '/patterns/application/composite' },
            { text: '享元模式（对象池/连接池）', link: '/patterns/application/flyweight' },
            { text: '行为型模式总览', link: '/patterns/application/behavioral' },
            { text: '策略模式（算法族/运行时切换）', link: '/patterns/application/strategy' },
            { text: '观察者模式（事件监听/发布订阅）', link: '/patterns/application/observer' },
            { text: '模板方法模式（钩子方法/好莱坞原则）', link: '/patterns/application/template' },
            { text: '责任链模式（过滤器链/拦截器）', link: '/patterns/application/chain' },
            { text: '状态模式（有限状态机）', link: '/patterns/application/state' },
            { text: '命令模式（请求封装/撤销重做）', link: '/patterns/application/command' },
            { text: '迭代器模式', link: '/patterns/application/iterator' },
            { text: '中介者模式', link: '/patterns/application/mediator' },
            { text: '备忘录模式（快照/撤销）', link: '/patterns/application/memento' },
            { text: '访问者模式（双分派）', link: '/patterns/application/visitor' },
            { text: '解释器模式', link: '/patterns/application/interpreter' },
        ],
    },
    {
        text: '并发设计模式',
        link: '/patterns/concurrency/',
        items: [
            { text: 'Worker Pool 线程池模式', link: '/patterns/concurrency/worker-pool' },
            { text: 'Pipeline 流水线模式', link: '/patterns/concurrency/pipeline' },
            { text: 'Thread Local 线程局部存储', link: '/patterns/concurrency/thread-local' },
            { text: '生产者-消费者模式', link: '/patterns/concurrency/producer-consumer' },
            { text: 'Future/Promise 异步模式', link: '/patterns/concurrency/future-promise' },
            { text: 'Fork/Join 分治模式', link: '/patterns/concurrency/fork-join' },
            { text: 'Active Object 主动对象模式', link: '/patterns/concurrency/active-object' },
            { text: 'Monitor Object 监视器模式', link: '/patterns/concurrency/monitor' },
            { text: '读写锁模式', link: '/patterns/concurrency/read-write-lock' },
            { text: 'Guarded Suspension 保护暂停', link: '/patterns/concurrency/guarded-suspension' },
            { text: 'Balking 模式', link: '/patterns/concurrency/balking' },
            { text: 'Double-Checked Locking 双重检查锁', link: '/patterns/concurrency/double-checked-locking' },
        ],
    },
    {
        text: '分布式模式',
        link: '/patterns/distributed/',
        items: [
            { text: 'Sidecar 边车模式', link: '/patterns/distributed/sidecar' },
            { text: 'Ambassador 大使模式', link: '/patterns/distributed/ambassador' },
            { text: 'Adapter 适配器模式（容器化场景）', link: '/patterns/distributed/adapter' },
            { text: 'Leader-Follower 领导者追随者模式', link: '/patterns/distributed/leader-follower' },
            { text: 'Work Queue 工作队列模式', link: '/patterns/distributed/work-queue' },
            { text: 'Scatter-Gather 散聚模式', link: '/patterns/distributed/scatter-gather' },
            { text: 'Pipeline 管道模式（分布式版）', link: '/patterns/distributed/pipeline' },
            { text: 'Sharding 分片模式', link: '/patterns/distributed/sharding' },
            { text: 'Replicated Load-Balanced Services', link: '/patterns/distributed/replicated-lb' },
            { text: 'Strangler Fig 绞杀者模式', link: '/patterns/distributed/strangler-fig' },
        ],
    },
    {
        text: '架构风格',
        link: '/patterns/architectural-styles/',
        items: [
            { text: '分层架构（Layered Architecture）', link: '/patterns/architectural-styles/layered' },
            { text: '六边形架构（Hexagonal Architecture）', link: '/patterns/architectural-styles/hexagonal' },
            { text: '洋葱架构（Onion Architecture）', link: '/patterns/architectural-styles/onion' },
            { text: '整洁架构（Clean Architecture）', link: '/patterns/architectural-styles/clean' },
            { text: 'CQRS 命令查询职责分离', link: '/patterns/architectural-styles/cqrs' },
            { text: '事件溯源（Event Sourcing）', link: '/patterns/architectural-styles/event-sourcing' },
            { text: 'EDA 事件驱动架构', link: '/patterns/architectural-styles/eda' },
            { text: '微内核架构（Microkernel）', link: '/patterns/architectural-styles/microkernel' },
            { text: '管道-过滤器架构', link: '/patterns/architectural-styles/pipe-filter' },
            { text: 'MVC/MVP/MVVM 架构', link: '/patterns/architectural-styles/mvc-mvvm' },
            { text: 'REST 架构风格', link: '/patterns/architectural-styles/rest' },
            { text: 'GraphQL 架构风格', link: '/patterns/architectural-styles/graphql' },
        ],
    },
    {
        text: '微服务模式',
        link: '/patterns/microservices/',
        items: [
            { text: 'API 网关模式', link: '/patterns/microservices/api-gateway' },
            { text: '配置中心模式', link: '/patterns/microservices/config-center' },
            { text: '服务发现模式（客户端/服务端发现）', link: '/patterns/microservices/service-discovery' },
            { text: '断路器模式', link: '/patterns/microservices/circuit-breaker' },
            { text: '服务注册中心（Eureka/Consul/Nacos）', link: '/patterns/microservices/registry' },
            { text: '负载均衡模式（服务端/客户端）', link: '/patterns/microservices/lb-pattern' },
            { text: '分布式配置（Spring Cloud Config）', link: '/patterns/microservices/distributed-config' },
            { text: '链路追踪模式', link: '/patterns/microservices/distributed-tracing' },
            { text: '边车模式（Service Mesh）', link: '/patterns/microservices/sidecar' },
            { text: '重试模式（Retry）', link: '/patterns/microservices/retry' },
            { text: '隔板模式（Bulkhead）', link: '/patterns/microservices/bulkhead' },
            { text: '健康检查模式', link: '/patterns/microservices/health-check' },
            { text: '外部化配置模式', link: '/patterns/microservices/external-config' },
            { text: '遥测监控模式', link: '/patterns/microservices/telemetry' },
        ],
    },
    {
        text: '数据架构模式',
        link: '/patterns/data-architecture/',
        items: [
            { text: 'Saga 分布式事务模式', link: '/patterns/data-architecture/saga' },
            { text: 'CQRS 数据读写分离', link: '/patterns/data-architecture/cqrs-data' },
            { text: '事件溯源（Event Sourcing）详解', link: '/patterns/data-architecture/event-sourcing-deep' },
            { text: '数据分片（Sharding）模式', link: '/patterns/data-architecture/sharding' },
            { text: '数据库分库分表', link: '/patterns/data-architecture/sharding-db' },
            { text: '读写分离模式', link: '/patterns/data-architecture/read-write-split' },
            { text: '数据复制模式（主从/多主/无主）', link: '/patterns/data-architecture/replication' },
            { text: 'CQRS + Event Sourcing 组合实战', link: '/patterns/data-architecture/cqrs-es' },
            { text: '数据归档与清理模式', link: '/patterns/data-architecture/archive' },
            { text: '多租户数据架构', link: '/patterns/data-architecture/multi-tenant' },
            { text: '数据版本化模式', link: '/patterns/data-architecture/versioning' },
            { text: '变更数据捕获（CDC）', link: '/patterns/data-architecture/cdc' },
        ],
    }
]