export const performanceJvmSidebar = [
    {
        text: '性能指标',
        link: '/performance-jvm/metrics/',
        items: [
            { text: '性能指标体系全景', link: '/performance-jvm/metrics/overview' },
            { text: '延迟（Latency）：P99/P999/P9999 详解', link: '/performance-jvm/metrics/latency' },
            { text: '吞吐量（Throughput）：QPS/TPS/RPS', link: '/performance-jvm/metrics/throughput' },
            { text: '并发用户数（Concurrency）', link: '/performance-jvm/metrics/concurrency' },
            { text: 'TP（Top Percentile）指标详解', link: '/performance-jvm/metrics/tp' },
            { text: 'SLA/SLO/SLI 与性能目标设定', link: '/performance-jvm/metrics/sla-slo-sli' },
            { text: '可用性与性能的关系', link: '/performance-jvm/metrics/availability' },
            { text: '性能基准测试（Benchmark）方法论', link: '/performance-jvm/metrics/benchmark' },
            { text: 'JMH（Java Microbenchmark Harness）实战', link: '/performance-jvm/metrics/jmh' },
            { text: '性能测试工具对比（JMeter/Locust/Gatling）', link: '/performance-jvm/metrics/testing-tools' },
        ],
    },
    {
        text: 'Java并发模型',
        link: '/performance-jvm/concurrency/',
        items: [
            { text: 'Java线程模型演进史', link: '/performance-jvm/concurrency/evolution' },
            { text: '平台线程（Platform Thread）详解', link: '/performance-jvm/concurrency/platform-thread' },
            { text: '线程生命周期与状态转换', link: '/performance-jvm/concurrency/thread-lifecycle' },
            { text: '线程池原理与最佳实践', link: '/performance-jvm/concurrency/thread-pool' },
            { text: 'Java内存模型（JMM）', link: '/performance-jvm/concurrency/jmm' },
            { text: 'happens-before 原则', link: '/performance-jvm/concurrency/happens-before' },
            { text: 'volatile 原理与内存屏障', link: '/performance-jvm/concurrency/volatile' },
            { text: 'synchronized 实现原理与优化', link: '/performance-jvm/concurrency/synchronized' },
            { text: '锁升级过程（无锁→偏向→轻量→重量）', link: '/performance-jvm/concurrency/lock-upgrade' },
            { text: 'AQS（AbstractQueuedSynchronizer）框架', link: '/performance-jvm/concurrency/aqs' },
            { text: 'ReentrantLock 与 Condition', link: '/performance-jvm/concurrency/reentrantlock' },
            { text: '读写锁（ReentrantReadWriteLock）', link: '/performance-jvm/concurrency/readwritelock' },
            { text: 'StampedLock 原理', link: '/performance-jvm/concurrency/stampedlock' },
            { text: 'CAS（Compare-And-Swap）与原子类', link: '/performance-jvm/concurrency/cas' },
            { text: 'LongAdder 与 AtomicLong 对比', link: '/performance-jvm/concurrency/longadder' },
            { text: 'CompletableFuture 异步编程', link: '/performance-jvm/concurrency/completablefuture' },
            { text: 'Fork/Join 框架详解', link: '/performance-jvm/concurrency/fork-join' },
            { text: '虚拟线程（Virtual Thread）深度解析', link: '/performance-jvm/concurrency/virtual-thread' },
            { text: 'Loom 项目架构与实现原理', link: '/performance-jvm/concurrency/loom' },
            { text: '虚拟线程 vs 平台线程性能对比', link: '/performance-jvm/concurrency/vt-vs-pt' },
            { text: '结构化并发（Structured Concurrency）', link: '/performance-jvm/concurrency/structured-concurrency' },
            { text: 'Scoped Values 作用域值', link: '/performance-jvm/concurrency/scoped-values' },
            { text: 'Java 21+ 并发新特性', link: '/performance-jvm/concurrency/java21-concurrency' },
            { text: '响应式编程（Reactive Programming）', link: '/performance-jvm/concurrency/reactive' },
            { text: 'Project Reactor 与 WebFlux', link: '/performance-jvm/concurrency/webflux' },
            { text: '并发编程常见陷阱与排查', link: '/performance-jvm/concurrency/pitfalls' },
        ],
    },
    {
        text: '内存模型与GC',
        link: '/performance-jvm/gc/',
        items: [
            { text: 'JVM 内存区域划分', link: '/performance-jvm/gc/memory-areas' },
            { text: '堆内存（Heap）详解', link: '/performance-jvm/gc/heap' },
            { text: '栈内存（Stack）与栈帧', link: '/performance-jvm/gc/stack' },
            { text: '方法区与元空间（Metaspace）', link: '/performance-jvm/gc/metaspace' },
            { text: '对象生命周期与内存分配', link: '/performance-jvm/gc/object-lifecycle' },
            { text: 'GC 基本原理：可达性分析', link: '/performance-jvm/gc/reachability' },
            { text: '引用类型（强/软/弱/虚引用）', link: '/performance-jvm/gc/reference-types' },
            { text: 'GC 算法：标记-清除', link: '/performance-jvm/gc/mark-sweep' },
            { text: 'GC 算法：复制算法', link: '/performance-jvm/gc/copying' },
            { text: 'GC 算法：标记-整理', link: '/performance-jvm/gc/mark-compact' },
            { text: '分代收集理论', link: '/performance-jvm/gc/generational' },
            { text: 'Serial/Serial Old 收集器', link: '/performance-jvm/gc/serial' },
            { text: 'ParNew 收集器', link: '/performance-jvm/gc/parnew' },
            { text: 'Parallel Scavenge 与 Parallel Old', link: '/performance-jvm/gc/parallel' },
            { text: 'CMS 收集器详解', link: '/performance-jvm/gc/cms' },
            { text: 'G1 收集器深度解析', link: '/performance-jvm/gc/g1' },
            { text: 'G1 核心：Region 与 Remembered Set', link: '/performance-jvm/gc/g1-region' },
            { text: 'G1 调优参数与实战', link: '/performance-jvm/gc/g1-tuning' },
            { text: 'ZGC 深度解析', link: '/performance-jvm/gc/zgc' },
            { text: 'ZGC 核心：染色指针与读屏障', link: '/performance-jvm/gc/zgc-colored-pointer' },
            { text: 'ZGC 调优参数与实战', link: '/performance-jvm/gc/zgc-tuning' },
            { text: 'Shenandoah GC 深度解析', link: '/performance-jvm/gc/shenandoah' },
            { text: 'Epsilon GC（无操作GC）', link: '/performance-jvm/gc/epsilon' },
            { text: 'GC 对比矩阵（G1/ZGC/Shenandoah）', link: '/performance-jvm/gc/comparison' },
            { text: 'GC 日志解读与分析', link: '/performance-jvm/gc/log-analysis' },
            { text: 'GC 调优方法论与案例', link: '/performance-jvm/gc/tuning' },
            { text: '内存泄漏排查实战', link: '/performance-jvm/gc/memory-leak' },
            { text: '堆转储（Heap Dump）分析', link: '/performance-jvm/gc/heap-dump' },
            { text: 'MAT 与 JProfiler 使用指南', link: '/performance-jvm/gc/profiling-tools' },
        ],
    },
    {
        text: 'JIT编译与AOT',
        link: '/performance-jvm/jit-aot/',
        items: [
            { text: 'JVM 执行引擎架构', link: '/performance-jvm/jit-aot/execution-engine' },
            { text: '字节码与解释执行', link: '/performance-jvm/jit-aot/bytecode' },
            { text: 'JIT 编译器概述', link: '/performance-jvm/jit-aot/overview' },
            { text: 'C1 编译器（Client Compiler）', link: '/performance-jvm/jit-aot/c1' },
            { text: 'C2 编译器（Server Compiler）', link: '/performance-jvm/jit-aot/c2' },
            { text: '分层编译（Tiered Compilation）', link: '/performance-jvm/jit-aot/tiered-compilation' },
            { text: '热点代码探测（HotSpot Detection）', link: '/performance-jvm/jit-aot/hotspot-detection' },
            { text: '方法内联（Method Inlining）', link: '/performance-jvm/jit-aot/inlining' },
            { text: '逃逸分析（Escape Analysis）', link: '/performance-jvm/jit-aot/escape-analysis' },
            { text: '锁消除（Lock Elision）与锁粗化', link: '/performance-jvm/jit-aot/lock-optimization' },
            { text: '标量替换（Scalar Replacement）', link: '/performance-jvm/jit-aot/scalar-replacement' },
            { text: '栈上分配（Stack Allocation）', link: '/performance-jvm/jit-aot/stack-allocation' },
            { text: '空值检查消除', link: '/performance-jvm/jit-aot/null-check' },
            { text: '范围检查消除', link: '/performance-jvm/jit-aot/range-check' },
            { text: 'JIT 编译日志解读', link: '/performance-jvm/jit-aot/log-analysis' },
            { text: 'AOT 编译（Ahead-of-Time）', link: '/performance-jvm/jit-aot/aot' },
            { text: 'GraalVM 原生镜像', link: '/performance-jvm/jit-aot/graalvm' },
            { text: 'JIT vs AOT 对比', link: '/performance-jvm/jit-aot/jit-vs-aot' },
            { text: 'Spring Native 与 Quarkus', link: '/performance-jvm/jit-aot/spring-native' },
            { text: 'JVM 启动优化技术', link: '/performance-jvm/jit-aot/startup-optimization' },
            { text: 'CDS（Class Data Sharing）', link: '/performance-jvm/jit-aot/cds' },
            { text: 'AppCDS 应用类数据共享', link: '/performance-jvm/jit-aot/appcds' },
        ],
    },
    {
        text: 'I/O模型',
        link: '/performance-jvm/io/',
        items: [
            { text: 'I/O 模型概述', link: '/performance-jvm/io/overview' },
            { text: '阻塞 I/O（BIO）', link: '/performance-jvm/io/bio' },
            { text: '非阻塞 I/O（NIO）', link: '/performance-jvm/io/nio' },
            { text: 'Channel 与 Buffer 详解', link: '/performance-jvm/io/channel-buffer' },
            { text: 'Selector 多路复用器', link: '/performance-jvm/io/selector' },
            { text: 'I/O 多路复用（epoll/kqueue/IOCP）', link: '/performance-jvm/io/multiplexing' },
            { text: '异步 I/O（AIO）', link: '/performance-jvm/io/aio' },
            { text: 'BIO/NIO/AIO 对比', link: '/performance-jvm/io/comparison' },
            { text: '零拷贝（Zero-Copy）原理', link: '/performance-jvm/io/zero-copy' },
            { text: 'mmap 内存映射文件', link: '/performance-jvm/io/mmap' },
            { text: 'sendfile 与 transferTo', link: '/performance-jvm/io/sendfile' },
            { text: 'Netty 架构深度解析', link: '/performance-jvm/io/netty' },
            { text: 'Netty 线程模型（Reactor）', link: '/performance-jvm/io/netty-thread-model' },
            { text: 'Netty 零拷贝实现', link: '/performance-jvm/io/netty-zero-copy' },
            { text: 'Java NIO 与 Netty 性能对比', link: '/performance-jvm/io/nio-vs-netty' },
            { text: '文件 I/O 优化', link: '/performance-jvm/io/file-io' },
            { text: '网络 I/O 优化', link: '/performance-jvm/io/network-io' },
            { text: '直接内存（Direct Memory）', link: '/performance-jvm/io/direct-memory' },
            { text: 'I/O 性能监控与诊断', link: '/performance-jvm/io/monitoring' },
        ],
    },
    {
        text: '性能剖析',
        link: '/performance-jvm/profiling/',
        items: [
            { text: '性能剖析方法论', link: '/performance-jvm/profiling/methodology' },
            { text: '采样 vs 插桩（Sampling vs Instrumentation）', link: '/performance-jvm/profiling/sampling-vs-instrumentation' },
            { text: 'CPU Profiling 火焰图', link: '/performance-jvm/profiling/flame-graph' },
            { text: '内存 Profiling', link: '/performance-jvm/profiling/memory-profiling' },
            { text: '堆内存分析工具（MAT/JProfiler/VisualVM）', link: '/performance-jvm/profiling/heap-analysis' },
            { text: '异步日志（Async Logger）原理', link: '/performance-jvm/profiling/async-logger' },
            { text: 'Log4j2 异步日志配置', link: '/performance-jvm/profiling/log4j2-async' },
            { text: 'JFR（Java Flight Recorder）详解', link: '/performance-jvm/profiling/jfr' },
            { text: 'JMC（Java Mission Control）使用', link: '/performance-jvm/profiling/jmc' },
            { text: 'Arthas 诊断工具实战', link: '/performance-jvm/profiling/arthas' },
            { text: 'SkyWalking/APM 集成', link: '/performance-jvm/profiling/apm' },
            { text: '持续性能分析（Continuous Profiling）', link: '/performance-jvm/profiling/continuous-profiling' },
            { text: 'Pyroscope 与 Polar Signals', link: '/performance-jvm/profiling/pyroscope' },
            { text: '性能优化案例：高延迟排查', link: '/performance-jvm/profiling/latency-case' },
            { text: '性能优化案例：CPU 飙升排查', link: '/performance-jvm/profiling/cpu-case' },
            { text: '性能优化案例：内存泄漏排查', link: '/performance-jvm/profiling/memory-case' },
            { text: '性能优化案例：GC 频繁排查', link: '/performance-jvm/profiling/gc-case' },
            { text: '性能优化案例：线程死锁排查', link: '/performance-jvm/profiling/deadlock-case' },
            { text: '全链路性能优化方法论', link: '/performance-jvm/profiling/end-to-end' },
        ],
    },
]