export const resilienceSidebar = [
    {
        text: '可用性理论',
        link: '/resilience/theory/',
        items: [
            { text: '可用性定义与度量', link: '/resilience/theory/definition' },
            { text: 'SLA（服务等级协议）详解', link: '/resilience/theory/sla' },
            { text: 'SLO（服务等级目标）设定', link: '/resilience/theory/slo' },
            { text: 'SLI（服务等级指标）选择', link: '/resilience/theory/sli' },
            { text: '错误预算（Error Budget）管理', link: '/resilience/theory/error-budget' },
            { text: 'MTBF/MTTR/MTTF 指标', link: '/resilience/theory/mtbf-mttr' },
            { text: '可用性等级（N个9）计算', link: '/resilience/theory/nines' },
            { text: '可用性目标与成本权衡', link: '/resilience/theory/cost-tradeoff' },
            { text: '可用性设计原则', link: '/resilience/theory/principles' },
        ],
    },
    {
        text: '故障模型',
        link: '/resilience/failure-models/',
        items: [
            { text: '故障模型概述', link: '/resilience/failure-models/overview' },
            { text: '崩溃故障（Crash Failure）', link: '/resilience/failure-models/crash' },
            { text: '遗漏故障（Omission Failure）', link: '/resilience/failure-models/omission' },
            { text: '拜占庭故障（Byzantine Failure）', link: '/resilience/failure-models/byzantine' },
            { text: '网络分区故障（Network Partition）', link: '/resilience/failure-models/network-partition' },
            { text: '超时故障（Timeout Failure）', link: '/resilience/failure-models/timeout' },
            { text: '性能故障（Performance Failure）', link: '/resilience/failure-models/performance' },
            { text: '故障检测机制', link: '/resilience/failure-models/detection' },
            { text: '故障分类与处理策略矩阵', link: '/resilience/failure-models/classification' },
        ],
    },
    {
        text: '容错模式',
        link: '/resilience/patterns/',
        items: [
            { text: '容错模式全景', link: '/resilience/patterns/overview' },
            { text: '熔断器模式（Circuit Breaker）', link: '/resilience/patterns/circuit-breaker' },
            { text: '熔断器状态机与实现', link: '/resilience/patterns/circuit-breaker-state' },
            { text: 'Resilience4j 熔断器实战', link: '/resilience/patterns/resilience4j' },
            { text: '限流模式（Rate Limiting）', link: '/resilience/patterns/rate-limiting' },
            { text: '令牌桶算法实现', link: '/resilience/patterns/token-bucket' },
            { text: '漏桶算法实现', link: '/resilience/patterns/leaky-bucket' },
            { text: '滑动窗口限流', link: '/resilience/patterns/sliding-window' },
            { text: '分布式限流（Redis + Lua）', link: '/resilience/patterns/distributed-rate-limit' },
            { text: 'Sentinel 限流降级实战', link: '/resilience/patterns/sentinel' },
            { text: '降级模式（Degradation）', link: '/resilience/patterns/degradation' },
            { text: '降级策略：返回默认值/空结果/缓存', link: '/resilience/patterns/degradation-strategies' },
            { text: '重试模式（Retry）', link: '/resilience/patterns/retry' },
            { text: '退避策略（Exponential Backoff）', link: '/resilience/patterns/backoff' },
            { text: '重试风暴与防范', link: '/resilience/patterns/retry-storm' },
            { text: '超时模式（Timeout）', link: '/resilience/patterns/timeout' },
            { text: '超时配置最佳实践', link: '/resilience/patterns/timeout-config' },
            { text: '舱壁隔离模式（Bulkhead）', link: '/resilience/patterns/bulkhead' },
            { text: '线程池舱壁 vs 信号量舱壁', link: '/resilience/patterns/bulkhead-types' },
            { text: '隔板模式实现', link: '/resilience/patterns/bulkhead-implementation' },
            { text: '故障切换（Failover）', link: '/resilience/patterns/failover' },
            { text: '快速失败（Fail Fast）', link: '/resilience/patterns/fail-fast' },
            { text: '静默失败（Fail Silent）', link: '/resilience/patterns/fail-silent' },
            { text: '容错模式组合使用', link: '/resilience/patterns/composition' },
            { text: '容错配置最佳实践', link: '/resilience/patterns/best-practices' },
        ],
    },
    {
        text: '健康检查与自愈',
        link: '/resilience/health-check/',
        items: [
            { text: '健康检查概述', link: '/resilience/health-check/overview' },
            { text: '存活探针（Liveness Probe）', link: '/resilience/health-check/liveness' },
            { text: '就绪探针（Readiness Probe）', link: '/resilience/health-check/readiness' },
            { text: '启动探针（Startup Probe）', link: '/resilience/health-check/startup' },
            { text: '探针实现最佳实践', link: '/resilience/health-check/probe-best-practices' },
            { text: '健康检查端点设计', link: '/resilience/health-check/endpoint-design' },
            { text: 'Spring Boot Actuator 健康检查', link: '/resilience/health-check/spring-actuator' },
            { text: 'Kubernetes 探针配置', link: '/resilience/health-check/k8s-probes' },
            { text: '优雅关闭（Graceful Shutdown）', link: '/resilience/health-check/graceful-shutdown' },
            { text: '优雅关闭实现方案', link: '/resilience/health-check/graceful-shutdown-implementation' },
            { text: '流量预热与冷启动', link: '/resilience/health-check/warm-up' },
            { text: '自愈机制设计', link: '/resilience/health-check/self-healing' },
            { text: '自动重启与重调度', link: '/resilience/health-check/auto-restart' },
        ],
    },
    {
        text: '混沌工程',
        link: '/resilience/chaos-engineering/',
        items: [
            { text: '混沌工程概述', link: '/resilience/chaos-engineering/overview' },
            { text: '混沌工程 vs 测试', link: '/resilience/chaos-engineering/vs-testing' },
            { text: '混沌工程原则', link: '/resilience/chaos-engineering/principles' },
            { text: '爆炸半径（Blast Radius）控制', link: '/resilience/chaos-engineering/blast-radius' },
            { text: '稳态假设（Steady State Hypothesis）', link: '/resilience/chaos-engineering/steady-state' },
            { text: '故障注入技术', link: '/resilience/chaos-engineering/fault-injection' },
            { text: '基础设施故障注入', link: '/resilience/chaos-engineering/infra-injection' },
            { text: '应用层故障注入', link: '/resilience/chaos-engineering/app-injection' },
            { text: '混沌工程工具对比', link: '/resilience/chaos-engineering/tools-comparison' },
            { text: 'Chaos Mesh 深度解析', link: '/resilience/chaos-engineering/chaos-mesh' },
            { text: 'ChaosBlade 使用指南', link: '/resilience/chaos-engineering/chaosblade' },
            { text: 'Gremlin 混沌工程平台', link: '/resilience/chaos-engineering/gremlin' },
            { text: '混沌实验设计流程', link: '/resilience/chaos-engineering/experiment-design' },
            { text: '混沌实验自动化', link: '/resilience/chaos-engineering/automation' },
            { text: '混沌工程度量指标', link: '/resilience/chaos-engineering/metrics' },
            { text: '混沌工程案例：Netflix Chaos Monkey', link: '/resilience/chaos-engineering/netflix' },
            { text: '混沌工程案例：阿里 ChaosBlade', link: '/resilience/chaos-engineering/alibaba' },
            { text: '生产环境混沌工程实践', link: '/resilience/chaos-engineering/production' },
        ],
    },
    {
        text: '备份与灾难恢复',
        link: '/resilience/disaster-recovery/',
        items: [
            { text: '灾难恢复概述', link: '/resilience/disaster-recovery/overview' },
            { text: 'RPO（恢复点目标）详解', link: '/resilience/disaster-recovery/rpo' },
            { text: 'RTO（恢复时间目标）详解', link: '/resilience/disaster-recovery/rto' },
            { text: 'RPO/RTO 权衡与设定', link: '/resilience/disaster-recovery/rpo-rto-tradeoff' },
            { text: '备份策略设计', link: '/resilience/disaster-recovery/backup-strategies' },
            { text: '全量备份与增量备份', link: '/resilience/disaster-recovery/full-incremental' },
            { text: '冷备份/温备份/热备份', link: '/resilience/disaster-recovery/backup-types' },
            { text: '数据备份工具对比', link: '/resilience/disaster-recovery/backup-tools' },
            { text: '异地多活架构', link: '/resilience/disaster-recovery/multi-active' },
            { text: '主备架构（Active-Standby）', link: '/resilience/disaster-recovery/active-standby' },
            { text: '双活架构（Active-Active）', link: '/resilience/disaster-recovery/active-active' },
            { text: '单元化架构（Unit Architecture）', link: '/resilience/disaster-recovery/unit-architecture' },
            { text: '单元化架构设计', link: '/resilience/disaster-recovery/unit-design' },
            { text: '同城双活 vs 两地三中心', link: '/resilience/disaster-recovery/disaster-levels' },
            { text: '故障演练与切换', link: '/resilience/disaster-recovery/failover-drill' },
            { text: '数据同步技术（CDC/主从复制）', link: '/resilience/disaster-recovery/data-sync' },
            { text: '容灾架构成本分析', link: '/resilience/disaster-recovery/cost-analysis' },
            { text: '灾难恢复计划（DRP）编写', link: '/resilience/disaster-recovery/drp' },
            { text: '容灾认证与合规', link: '/resilience/disaster-recovery/compliance' },
        ],
    },
];