export const securitySidebar = [
    {
        text: '身份与访问管理',
        link: '/security/iam/',
        items: [
            { text: 'IAM 概述与核心概念', link: '/security/iam/overview' },
            { text: '认证（Authentication）与授权（Authorization）', link: '/security/iam/authn-authz' },
            { text: 'OAuth 2.0 协议深度解析', link: '/security/iam/oauth2' },
            { text: 'OAuth 2.0 四种授权模式', link: '/security/iam/oauth2-grant-types' },
            { text: 'OAuth 2.0 安全最佳实践', link: '/security/iam/oauth2-security' },
            { text: 'OIDC（OpenID Connect）深度解析', link: '/security/iam/oidc' },
            { text: 'OAuth2 vs OIDC 对比', link: '/security/iam/oauth2-vs-oidc' },
            { text: 'SAML 2.0 协议深度解析', link: '/security/iam/saml' },
            { text: 'SAML vs OIDC 选型对比', link: '/security/iam/saml-vs-oidc' },
            { text: 'JWT（JSON Web Token）深度解析', link: '/security/iam/jwt' },
            { text: 'JWT 签名与加密', link: '/security/iam/jwt-sign-encrypt' },
            { text: 'JWT 安全风险与防范', link: '/security/iam/jwt-security' },
            { text: 'SSO（单点登录）架构设计', link: '/security/iam/sso' },
            { text: 'SSO 实现方案对比', link: '/security/iam/sso-comparison' },
            { text: 'Keycloak 深度解析', link: '/security/iam/keycloak' },
            { text: 'Keycloak 部署与配置', link: '/security/iam/keycloak-deployment' },
            { text: 'Spring Security OAuth2 实战', link: '/security/iam/spring-security-oauth2' },
            { text: 'LDAP 与 Active Directory', link: '/security/iam/ldap' },
            { text: '多因素认证（MFA）设计', link: '/security/iam/mfa' },
            { text: '生物认证与 WebAuthn', link: '/security/iam/webauthn' },
            { text: '身份联邦（Identity Federation）', link: '/security/iam/federation' },
            { text: '零信任身份架构', link: '/security/iam/zero-trust-identity' },
        ],
    },
    {
        text: '权限模型',
        link: '/security/authorization/',
        items: [
            { text: '授权模型概述', link: '/security/authorization/overview' },
            { text: 'RBAC（基于角色的访问控制）', link: '/security/authorization/rbac' },
            { text: 'RBAC 设计最佳实践', link: '/security/authorization/rbac-best-practices' },
            { text: 'ABAC（基于属性的访问控制）', link: '/security/authorization/abac' },
            { text: 'ABAC 策略设计', link: '/security/authorization/abac-policies' },
            { text: 'RBAC vs ABAC 对比', link: '/security/authorization/rbac-vs-abac' },
            { text: 'ReBAC（基于关系的访问控制）', link: '/security/authorization/rebac' },
            { text: 'Google Zanzibar 论文解析', link: '/security/authorization/zanzibar' },
            { text: 'OPA（Open Policy Agent）深度解析', link: '/security/authorization/opa' },
            { text: 'Rego 策略语言语法', link: '/security/authorization/rego' },
            { text: 'OPA 集成实战', link: '/security/authorization/opa-integration' },
            { text: 'OPA 与 Kubernetes 集成', link: '/security/authorization/opa-k8s' },
            { text: 'Casbin 权限框架', link: '/security/authorization/casbin' },
            { text: 'Casbin 模型配置', link: '/security/authorization/casbin-model' },
            { text: '权限审计与日志', link: '/security/authorization/audit' },
            { text: '权限缓存与性能优化', link: '/security/authorization/caching' },
            { text: '分布式权限设计', link: '/security/authorization/distributed' },
            { text: 'API 网关权限控制', link: '/security/authorization/api-gateway' },
        ],
    },
    {
        text: '密码学应用',
        link: '/security/cryptography/',
        items: [
            { text: '密码学基础概述', link: '/security/cryptography/overview' },
            { text: '对称加密算法（AES/ChaCha20）', link: '/security/cryptography/symmetric' },
            { text: 'AES 加密模式（ECB/CBC/GCM）', link: '/security/cryptography/aes-modes' },
            { text: '非对称加密算法（RSA/ECC）', link: '/security/cryptography/asymmetric' },
            { text: 'RSA 原理与最佳实践', link: '/security/cryptography/rsa' },
            { text: 'ECC 椭圆曲线密码学', link: '/security/cryptography/ecc' },
            { text: '哈希算法（SHA/MD5/Bcrypt）', link: '/security/cryptography/hash' },
            { text: '密码存储最佳实践（加盐/迭代）', link: '/security/cryptography/password-storage' },
            { text: '数字签名（RSA/ECDSA）', link: '/security/cryptography/digital-signature' },
            { text: 'TLS/SSL 协议深度解析', link: '/security/cryptography/tls' },
            { text: 'TLS 握手流程详解', link: '/security/cryptography/tls-handshake' },
            { text: 'TLS 版本对比（1.2 vs 1.3）', link: '/security/cryptography/tls-versions' },
            { text: '证书与 PKI（公钥基础设施）', link: '/security/cryptography/pki' },
            { text: 'CA 证书签发与管理', link: '/security/cryptography/ca' },
            { text: 'mTLS（双向 TLS）', link: '/security/cryptography/mtls' },
            { text: 'HSM（硬件安全模块）', link: '/security/cryptography/hsm' },
            { text: '密钥管理（KMS）最佳实践', link: '/security/cryptography/kms' },
            { text: '密钥轮转策略', link: '/security/cryptography/key-rotation' },
            { text: '国密算法（SM2/SM3/SM4）', link: '/security/cryptography/sm' },
            { text: '量子计算对密码学的挑战', link: '/security/cryptography/quantum' },
        ],
    },
    {
        text: 'API安全',
        link: '/security/api/',
        items: [
            { text: 'API 安全概述', link: '/security/api/overview' },
            { text: 'API 认证最佳实践', link: '/security/api/authentication' },
            { text: 'API Key 与 Token 管理', link: '/security/api/api-key' },
            { text: 'JWT 安全使用指南', link: '/security/api/jwt-security' },
            { text: 'API 限流（Rate Limiting）设计', link: '/security/api/rate-limiting' },
            { text: '防重放攻击（Anti-Replay）', link: '/security/api/anti-replay' },
            { text: 'Nonce 与 Timestamp 机制', link: '/security/api/nonce-timestamp' },
            { text: '签名机制设计', link: '/security/api/signature' },
            { text: '图灵盾（Turing Shield）与反爬', link: '/security/api/turing-shield' },
            { text: 'API 注入攻击防护', link: '/security/api/injection' },
            { text: 'GraphQL 安全', link: '/security/api/graphql-security' },
            { text: 'REST API 安全清单', link: '/security/api/rest-security-checklist' },
            { text: 'API 版本控制与安全', link: '/security/api/versioning' },
            { text: 'API 网关安全配置', link: '/security/api/gateway-security' },
            { text: 'API 安全测试', link: '/security/api/security-testing' },
            { text: 'OWASP API Security Top 10', link: '/security/api/owasp-top10' },
            { text: 'API 安全监控与告警', link: '/security/api/monitoring' },
        ],
    },
    {
        text: '网络安全',
        link: '/security/network/',
        items: [
            { text: '网络安全概述', link: '/security/network/overview' },
            { text: '零信任网络架构（ZTNA）', link: '/security/network/ztna' },
            { text: '零信任核心原则与实施', link: '/security/network/zero-trust-principles' },
            { text: 'BeyondCorp 架构解析', link: '/security/network/beyondcorp' },
            { text: '微分段（Micro-Segmentation）', link: '/security/network/micro-segmentation' },
            { text: '微分段技术对比', link: '/security/network/segmentation-comparison' },
            { text: 'WAF（Web应用防火墙）', link: '/security/network/waf' },
            { text: 'WAF 规则配置与绕过防护', link: '/security/network/waf-rules' },
            { text: 'DDOS 攻击类型与防护', link: '/security/network/ddos' },
            { text: 'DDOS 防护策略（清洗/限流/黑洞）', link: '/security/network/ddos-protection' },
            { text: '网络隔离与分段', link: '/security/network/isolation' },
            { text: 'VPN 技术（IPsec/OpenVPN/WireGuard）', link: '/security/network/vpn' },
            { text: 'IDS/IPS 入侵检测与防御', link: '/security/network/ids-ips' },
            { text: '网络流量分析（NTA）', link: '/security/network/nta' },
            { text: 'DNS 安全（DNSSEC/DNS over TLS）', link: '/security/network/dns-security' },
            { text: '安全组与网络 ACL', link: '/security/network/security-group' },
            { text: 'BGP 路由安全（RPKI）', link: '/security/network/bgp-security' },
        ],
    },
    {
        text: '应用安全',
        link: '/security/application/',
        items: [
            { text: '应用安全概述', link: '/security/application/overview' },
            { text: 'SDL（安全开发生命周期）', link: '/security/application/sdl' },
            { text: '威胁建模（Threat Modeling）', link: '/security/application/threat-modeling' },
            { text: 'STRIDE 威胁模型', link: '/security/application/stride' },
            { text: 'SQL 注入原理与防护', link: '/security/application/sql-injection' },
            { text: 'XSS（跨站脚本攻击）', link: '/security/application/xss' },
            { text: 'XSS 防护（CSP/转义）', link: '/security/application/xss-protection' },
            { text: 'CSRF（跨站请求伪造）', link: '/security/application/csrf' },
            { text: 'CSRF 防护（Token/SameSite）', link: '/security/application/csrf-protection' },
            { text: 'SSRF（服务端请求伪造）', link: '/security/application/ssrf' },
            { text: '路径遍历与文件上传漏洞', link: '/security/application/file-upload' },
            { text: 'XXE（XML外部实体注入）', link: '/security/application/xxe' },
            { text: '反序列化漏洞', link: '/security/application/deserialization' },
            { text: '日志注入与敏感信息泄露', link: '/security/application/log-injection' },
            { text: '依赖扫描（SCA）', link: '/security/application/sca' },
            { text: 'SAST（静态应用安全测试）', link: '/security/application/sast' },
            { text: 'DAST（动态应用安全测试）', link: '/security/application/dast' },
            { text: 'IAST（交互式应用安全测试）', link: '/security/application/iast' },
            { text: 'RASP（运行时应用自我保护）', link: '/security/application/rasp' },
            { text: '安全代码审计指南', link: '/security/application/code-audit' },
            { text: '漏洞修复优先级排序', link: '/security/application/vulnerability-prioritization' },
            { text: 'OWASP Top 10 详解', link: '/security/application/owasp-top10' },
        ],
    },
    {
        text: '云原生安全',
        link: '/security/cloud-native/',
        items: [
            { text: '云原生安全概述', link: '/security/cloud-native/overview' },
            { text: '云安全责任共担模型', link: '/security/cloud-native/shared-responsibility' },
            { text: '容器镜像安全扫描', link: '/security/cloud-native/image-scanning' },
            { text: '镜像签名与信任（Notary/Cosign）', link: '/security/cloud-native/image-signing' },
            { text: '容器运行时安全（Falco）', link: '/security/cloud-native/runtime-security' },
            { text: '容器逃逸防护', link: '/security/cloud-native/container-escape' },
            { text: 'Kubernetes RBAC 深度解析', link: '/security/cloud-native/k8s-rbac' },
            { text: 'Kubernetes 网络策略（NetworkPolicy）', link: '/security/cloud-native/k8s-network-policy' },
            { text: 'Pod 安全策略（PSP/PSS）', link: '/security/cloud-native/pod-security' },
            { text: 'Kubernetes Secret 管理', link: '/security/cloud-native/k8s-secret' },
            { text: 'Kubernetes 审计日志', link: '/security/cloud-native/k8s-audit' },
            { text: 'Kubernetes 攻击面分析', link: '/security/cloud-native/k8s-attack-surface' },
            { text: 'OPA Gatekeeper 策略即代码', link: '/security/cloud-native/opa-gatekeeper' },
            { text: '服务网格安全（mTLS/授权）', link: '/security/cloud-native/service-mesh-security' },
            { text: '云工作负载保护平台（CWPP）', link: '/security/cloud-native/cwpp' },
            { text: '云安全态势管理（CSPM）', link: '/security/cloud-native/cspm' },
            { text: 'Kube-bench 合规检查', link: '/security/cloud-native/kube-bench' },
            { text: 'Kube-hunter 安全渗透', link: '/security/cloud-native/kube-hunter' },
            { text: '容器环境供应链安全', link: '/security/cloud-native/supply-chain' },
            { text: 'SBOM（软件物料清单）', link: '/security/cloud-native/sbom' },
            { text: '云原生安全工具链', link: '/security/cloud-native/toolchain' },
        ],
    },
    {
        text: '合规与隐私',
        link: '/security/compliance/',
        items: [
            { text: '合规概述与重要性', link: '/security/compliance/overview' },
            { text: 'GDPR（通用数据保护条例）', link: '/security/compliance/gdpr' },
            { text: 'GDPR 合规要点', link: '/security/compliance/gdpr-compliance' },
            { text: 'CCPA（加州消费者隐私法案）', link: '/security/compliance/ccpa' },
            { text: '中国等保（等级保护）2.0', link: '/security/compliance/djcp' },
            { text: '等保定级与测评', link: '/security/compliance/djcp-assessment' },
            { text: 'SOC 2 审计报告', link: '/security/compliance/soc2' },
            { text: 'SOC 2 信任服务原则', link: '/security/compliance/soc2-principles' },
            { text: 'ISO 27001 信息安全管理体系', link: '/security/compliance/iso27001' },
            { text: 'HIPAA（医疗信息保护）', link: '/security/compliance/hipaa' },
            { text: 'PCI DSS（支付卡行业安全标准）', link: '/security/compliance/pci-dss' },
            { text: '数据脱敏（Data Masking）技术', link: '/security/compliance/data-masking' },
            { text: '动态脱敏 vs 静态脱敏', link: '/security/compliance/dynamic-static-masking' },
            { text: '数据分类分级', link: '/security/compliance/data-classification' },
            { text: '数据留存与删除策略', link: '/security/compliance/data-retention' },
            { text: '隐私影响评估（PIA）', link: '/security/compliance/pia' },
            { text: '隐私设计（Privacy by Design）', link: '/security/compliance/privacy-by-design' },
            { text: '跨境数据传输合规', link: '/security/compliance/cross-border' },
            { text: '安全审计与日志保留', link: '/security/compliance/audit-logging' },
            { text: '合规自动化工具', link: '/security/compliance/automation-tools' },
        ],
    },
];