export const securitySidebar = [
  {
    text: '身份与访问控制',
    link: '/security/iam/',
    items: [
      { text: '认证 vs 授权', link: '/security/iam/authentication-authorization' },
      { text: 'Session 认证', link: '/security/iam/session' },
      { text: 'JWT 认证', link: '/security/iam/jwt' },
      { text: 'OAuth 2.0 原理', link: '/security/iam/oauth2' },
      { text: 'OpenID Connect', link: '/security/iam/oidc' },
      { text: 'SSO 单点登录', link: '/security/iam/sso' },
      { text: '多因素认证', link: '/security/iam/mfa' },
      { text: 'LDAP 与目录服务', link: '/security/iam/ldap' },
    ],
  },
  {
    text: '权限管理',
    link: '/security/rbac/',
    items: [
      { text: 'RBAC 模型', link: '/security/rbac/rbac' },
      { text: 'ABAC 模型', link: '/security/rbac/abac' },
      { text: '权限模型选型', link: '/security/rbac/selection' },
      { text: '动态权限控制', link: '/security/rbac/dynamic-permission' },
      { text: '权限审计', link: '/security/rbac/audit' },
    ],
  },
  {
    text: '密码学与数据安全',
    link: '/security/data-security/',
    items: [
      { text: '对称加密', link: '/security/data-security/symmetric' },
      { text: '非对称加密', link: '/security/data-security/asymmetric' },
      { text: '哈希与消息认证', link: '/security/data-security/hash-mac' },
      { text: '数字签名与证书', link: '/security/data-security/sign-cert' },
      { text: '国密算法 SM2/SM3/SM4', link: '/security/data-security/gm' },
      { text: '密钥管理策略', link: '/security/data-security/key-management' },
      { text: '数据脱敏实战', link: '/security/data-security/masking' },
      { text: '敏感信息防护', link: '/security/data-security/sensitive-data' },
    ],
  },
  {
    text: '应用安全',
    link: '/security/application/',
    items: [
      { text: 'OWASP Top 10', link: '/security/application/owasp-top10' },
      { text: 'SQL 注入防护', link: '/security/application/sql-injection' },
      { text: 'XSS 跨站脚本', link: '/security/application/xss' },
      { text: 'CSRF 防护机制', link: '/security/application/csrf' },
      { text: '文件上传安全', link: '/security/application/file-upload' },
      { text: '命令注入防护', link: '/security/application/command-injection' },
    ],
  },
  {
    text: 'API 安全',
    link: '/security/api-security/',
    items: [
      { text: 'API 安全设计', link: '/security/api-security/api-design' },
      { text: 'API 签名机制', link: '/security/api-security/api-sign' },
      { text: '接口限流与防刷', link: '/security/api-security/rate-limit' },
      { text: '重放攻击防护', link: '/security/api-security/replay-attack' },
      { text: 'API 网关安全', link: '/security/api-security/api-gateway' },
    ],
  },
  {
    text: '网络安全',
    link: '/security/network/',
    items: [
      { text: 'TLS/SSL 实战', link: '/security/network/tls' },
      { text: 'DNS 安全', link: '/security/network/dns' },
      { text: 'CDN 安全配置', link: '/security/network/cdn' },
      { text: 'WAF 防护策略', link: '/security/network/waf' },
      { text: '网络隔离设计', link: '/security/network/isolation' },
      { text: 'DDoS 防护方案', link: '/security/network/ddos' },
    ],
  },
  {
    text: '云原生安全',
    link: '/security/cloud-security/',
    items: [
      { text: '云账号与权限安全', link: '/security/cloud-security/cloud-iam' },
      { text: '容器安全 Docker/K8s', link: '/security/cloud-security/container' },
      { text: '微服务安全架构', link: '/security/cloud-security/micro-service' },
      { text: '云配置安全 CSPM', link: '/security/cloud-security/cspm' },
    ],
  },
  {
    text: '基础设施安全',
    link: '/security/infra/',
    items: [
      { text: '服务器安全基线', link: '/security/infra/server-baseline' },
      { text: '端口与服务加固', link: '/security/infra/port-hardening' },
    ],
  },
  {
    text: '安全运营',
    link: '/security/secops/',
    items: [
      { text: '入侵检测 IDS/IPS', link: '/security/secops/ids-ips' },
      { text: '日志审计体系', link: '/security/secops/logging' },
      { text: '威胁情报应用', link: '/security/secops/threat-intel' },
      { text: '应急响应流程', link: '/security/secops/incident-response' },
      { text: '漏洞管理流程', link: '/security/secops/vulnerability' },
    ],
  },
  {
    text: '安全开发',
    link: '/security/sdl/',
    items: [
      { text: '威胁建模方法', link: '/security/sdl/threat-modeling' },
      { text: '安全编码规范', link: '/security/sdl/secure-coding' },
      { text: '代码审计要点', link: '/security/sdl/code-review' },
      { text: '第三方依赖安全', link: '/security/sdl/dependency' },
      { text: '安全测试策略', link: '/security/sdl/security-testing' },
    ],
  },
  {
    text: '安全合规',
    link: '/security/compliance/',
    items: [
      { text: '网络安全等级保护 2.0', link: '/security/compliance/level-protect' },
      { text: '个人信息保护 PIPL', link: '/security/compliance/pipl' },
      { text: 'GDPR 合规要点', link: '/security/compliance/gdpr' },
      { text: '安全合规自查清单', link: '/security/compliance/checklist' },
    ],
  },
  {
    text: '安全架构设计',
    link: '/security/architecture/',
    items: [
      { text: '零信任架构', link: '/security/architecture/zero-trust' },
      { text: '纵深防御体系', link: '/security/architecture/defense-in-depth' },
      { text: '最小权限原则', link: '/security/architecture/least-privilege' },
      { text: '失效安全设计', link: '/security/architecture/fail-safe' },
      { text: '安全架构评审', link: '/security/architecture/review' },
    ],
  },
  {
    text: '安全治理',
    link: '/security/governance/',
    items: [
      { text: '企业安全组织体系', link: '/security/governance/organization' },
      { text: '安全成熟度模型', link: '/security/governance/maturity' },
    ],
  },
];