export const systemDesignSidebar = [
    {
        text: '设计方法论',
        link: '/system-design/methodology/',
        items: [
            { text: '系统设计面试流程与框架', link: '/system-design/methodology/interview-framework' },
            { text: '需求分析：功能需求 vs 非功能需求', link: '/system-design/methodology/requirements' },
            { text: '用户故事与用例驱动设计', link: '/system-design/methodology/user-stories' },
            { text: '容量规划：QPS/TPS 估算方法', link: '/system-design/methodology/capacity-planning' },
            { text: '延迟估算：数字速算表（Back-of-the-envelope）', link: '/system-design/methodology/latency-estimation' },
            { text: '存储容量估算（数据量/索引/冗余）', link: '/system-design/methodology/storage-estimation' },
            { text: '带宽与网络规划', link: '/system-design/methodology/bandwidth-planning' },
            { text: '系统设计文档（SDD）编写规范', link: '/system-design/methodology/sdd' },
            { text: '架构评审 Checklist', link: '/system-design/methodology/review-checklist' },
        ],
    },
    {
        text: '权衡分析',
        link: '/system-design/tradeoffs/',
        items: [
            { text: '一致性 vs 可用性：PACELC 定理', link: '/system-design/tradeoffs/pacelc' },
            { text: '延迟 vs 吞吐量（Latency vs Throughput）', link: '/system-design/tradeoffs/latency-throughput' },
            { text: '读优化 vs 写优化（读重 vs 写重场景）', link: '/system-design/tradeoffs/read-vs-write' },
            { text: '强一致性 vs 最终一致性场景选择', link: '/system-design/tradeoffs/consistency-choices' },
            { text: '同步 vs 异步处理', link: '/system-design/tradeoffs/sync-vs-async' },
            { text: 'SQL vs NoSQL 选型矩阵', link: '/system-design/tradeoffs/sql-vs-nosql' },
            { text: '单体 vs 微服务权衡', link: '/system-design/tradeoffs/monolith-vs-microservices' },
            { text: '关系型 vs 非关系型数据库', link: '/system-design/tradeoffs/relational-vs-nonrelational' },
            { text: '批处理 vs 流处理', link: '/system-design/tradeoffs/batch-vs-stream' },
            { text: '推模式 vs 拉模式', link: '/system-design/tradeoffs/push-vs-pull' },
            { text: '状态ful vs 状态less设计', link: '/system-design/tradeoffs/stateful-vs-stateless' },
            { text: '成本 vs 性能的经济权衡', link: '/system-design/tradeoffs/cost-vs-performance' },
        ],
    },
    {
        text: '扩展策略',
        link: '/system-design/scaling/',
        items: [
            { text: '垂直扩展（Scale Up）', link: '/system-design/scaling/vertical' },
            { text: '水平扩展（Scale Out）', link: '/system-design/scaling/horizontal' },
            { text: '弹性伸缩（Auto-scaling）原理', link: '/system-design/scaling/auto-scaling' },
            { text: '无状态化设计（Stateless Design）', link: '/system-design/scaling/stateless' },
            { text: 'AKF 扩展立方体', link: '/system-design/scaling/akf-cube' },
            { text: 'X 轴扩展：水平复制', link: '/system-design/scaling/x-axis' },
            { text: 'Y 轴扩展：功能拆分（微服务）', link: '/system-design/scaling/y-axis' },
            { text: 'Z 轴扩展：数据分区（分片）', link: '/system-design/scaling/z-axis' },
            { text: '读写分离扩展', link: '/system-design/scaling/read-write-split' },
            { text: '计算与存储分离', link: '/system-design/scaling/compute-storage-separation' },
        ],
    },
    {
        text: '数据分片',
        link: '/system-design/sharding/',
        items: [
            { text: '分片策略总览', link: '/system-design/sharding/overview' },
            { text: '范围分片（Range Sharding）', link: '/system-design/sharding/range' },
            { text: '哈希分片（Hash Sharding）', link: '/system-design/sharding/hash' },
            { text: '一致性哈希原理与实现', link: '/system-design/sharding/consistent-hashing' },
            { text: '虚拟节点与负载均衡', link: '/system-design/sharding/virtual-nodes' },
            { text: '目录分片（Directory-Based Sharding）', link: '/system-design/sharding/directory' },
            { text: '地理分片（Geographic Sharding）', link: '/system-design/sharding/geo' },
            { text: '热点数据处理策略', link: '/system-design/sharding/hotspot' },
            { text: '分片键设计最佳实践', link: '/system-design/sharding/shard-key' },
            { text: '动态分片与重平衡', link: '/system-design/sharding/rebalancing' },
            { text: '分片带来的查询挑战', link: '/system-design/sharding/query-challenges' },
            { text: '分片与二级索引', link: '/system-design/sharding/secondary-index' },
            { text: '分片 vs 分区（Partitioning vs Sharding）', link: '/system-design/sharding/sharding-vs-partitioning' },
        ],
    },
    {
        text: '缓存策略',
        link: '/system-design/caching/',
        items: [
            { text: '缓存系统概述与收益分析', link: '/system-design/caching/overview' },
            { text: '本地缓存（Caffeine/Guava）', link: '/system-design/caching/local-cache' },
            { text: '分布式缓存（Redis/Memcached）', link: '/system-design/caching/distributed-cache' },
            { text: '多级缓存架构', link: '/system-design/caching/multi-level' },
            { text: '缓存穿透详解与解决方案', link: '/system-design/caching/penetration' },
            { text: '缓存击穿详解与解决方案', link: '/system-design/caching/breakdown' },
            { text: '缓存雪崩详解与解决方案', link: '/system-design/caching/avalanche' },
            { text: '布隆过滤器原理与应用', link: '/system-design/caching/bloom-filter' },
            { text: '缓存淘汰策略（LRU/LFU/FIFO/TTL）', link: '/system-design/caching/eviction' },
            { text: '缓存一致性（Cache Coherency）', link: '/system-design/caching/coherency' },
            { text: '写穿/写回/写旁路策略', link: '/system-design/caching/write-policies' },
            { text: '延迟双删详解', link: '/system-design/caching/delay-double-delete' },
            { text: '缓存预热与缓存刷新', link: '/system-design/caching/preheat-refresh' },
            { text: '缓存监控与指标', link: '/system-design/caching/monitoring' },
        ],
    },
    {
        text: '负载均衡',
        link: '/system-design/load-balancing/',
        items: [
            { text: '负载均衡概述', link: '/system-design/load-balancing/overview' },
            { text: '四层负载均衡（LVS/DPVS）', link: '/system-design/load-balancing/layer4' },
            { text: '七层负载均衡（Nginx/HAProxy）', link: '/system-design/load-balancing/layer7' },
            { text: '轮询与加权轮询算法', link: '/system-design/load-balancing/round-robin' },
            { text: '最小连接数与加权最小连接数', link: '/system-design/load-balancing/least-connections' },
            { text: 'IP Hash 与一致性哈希', link: '/system-design/load-balancing/ip-hash' },
            { text: '最短响应时间算法', link: '/system-design/load-balancing/least-time' },
            { text: '地理位置负载均衡（GSLB）', link: '/system-design/load-balancing/geo' },
            { text: '客户端负载均衡（Ribbon/Spring Cloud LB）', link: '/system-design/load-balancing/client-side' },
            { text: '服务端负载均衡（Nginx/K8s Ingress）', link: '/system-design/load-balancing/server-side' },
            { text: '健康检查机制（主动/被动）', link: '/system-design/load-balancing/health-check' },
            { text: '会话保持（Sticky Session）', link: '/system-design/load-balancing/sticky-session' },
            { text: '全局负载均衡与灾备', link: '/system-design/load-balancing/global' },
        ],
    },
    {
        text: '消息与流系统',
        link: '/system-design/messaging/',
        items: [
            { text: '消息队列核心概念', link: '/system-design/messaging/concepts' },
            { text: '点对点 vs 发布订阅模型', link: '/system-design/messaging/models' },
            { text: '消息顺序保证', link: '/system-design/messaging/ordering' },
            { text: '消息可靠性与确认机制', link: '/system-design/messaging/reliability' },
            { text: '死信队列与重试队列', link: '/system-design/messaging/dead-letter' },
            { text: '消息积压处理策略', link: '/system-design/messaging/backlog' },
            { text: 'Kafka 架构深度解析', link: '/system-design/messaging/kafka' },
            { text: 'Kafka 分区与消费者组', link: '/system-design/messaging/kafka-partition' },
            { text: 'Pulsar 架构深度解析', link: '/system-design/messaging/pulsar' },
            { text: 'RabbitMQ 架构深度解析', link: '/system-design/messaging/rabbitmq' },
            { text: 'RocketMQ 架构深度解析', link: '/system-design/messaging/rocketmq' },
            { text: '消息队列选型对比矩阵', link: '/system-design/messaging/comparison' },
            { text: '流处理 vs 批处理', link: '/system-design/messaging/stream-vs-batch' },
            { text: 'Exactly-Once 语义实现', link: '/system-design/messaging/exactly-once' },
            { text: '消息队列在微服务中的应用', link: '/system-design/messaging/microservices' },
        ],
    },
    {
        text: '存储引擎',
        link: '/system-design/storage-engine/',
        items: [
            { text: '存储引擎概述', link: '/system-design/storage-engine/overview' },
            { text: 'LSM Tree 原理详解', link: '/system-design/storage-engine/lsm-tree' },
            { text: 'SSTable 与 MemTable', link: '/system-design/storage-engine/sstable-memtable' },
            { text: 'WAL（预写日志）机制', link: '/system-design/storage-engine/wal' },
            { text: 'LSM Tree 的 Compaction 策略', link: '/system-design/storage-engine/compaction' },
            { text: 'B+ Tree 原理详解', link: '/system-design/storage-engine/bplus-tree' },
            { text: 'B+ Tree 与 LSM Tree 对比', link: '/system-design/storage-engine/comparison' },
            { text: '位图索引与倒排索引', link: '/system-design/storage-engine/inverted-index' },
            { text: '列式存储 vs 行式存储', link: '/system-design/storage-engine/column-vs-row' },
            { text: 'Bloom Filter 在存储引擎中的应用', link: '/system-design/storage-engine/bloom-filter-storage' },
            { text: 'RocksDB 架构解析', link: '/system-design/storage-engine/rocksdb' },
            { text: 'LevelDB 架构解析', link: '/system-design/storage-engine/leveldb' },
            { text: 'InnoDB 存储引擎架构', link: '/system-design/storage-engine/innodb' },
            { text: '存储引擎选型指南', link: '/system-design/storage-engine/selection' },
        ],
    },
]